package com.mission.shop.product.dao.model;

import java.io.Serializable;

public class AttrGroup implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attr_group.attr_group_id
	 * @mbggenerated  Mon Jul 28 21:25:09 CST 2014
	 */
	private Long attrGroupId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attr_group.kind_id
	 * @mbggenerated  Mon Jul 28 21:25:09 CST 2014
	 */
	private Long kindId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attr_group.group_name
	 * @mbggenerated  Mon Jul 28 21:25:09 CST 2014
	 */
	private String groupName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attr_group.status
	 * @mbggenerated  Mon Jul 28 21:25:09 CST 2014
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table attr_group
	 * @mbggenerated  Mon Jul 28 21:25:09 CST 2014
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attr_group.attr_group_id
	 * @return  the value of attr_group.attr_group_id
	 * @mbggenerated  Mon Jul 28 21:25:09 CST 2014
	 */
	public Long getAttrGroupId() {
		return attrGroupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attr_group.attr_group_id
	 * @param attrGroupId  the value for attr_group.attr_group_id
	 * @mbggenerated  Mon Jul 28 21:25:09 CST 2014
	 */
	public void setAttrGroupId(Long attrGroupId) {
		this.attrGroupId = attrGroupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attr_group.kind_id
	 * @return  the value of attr_group.kind_id
	 * @mbggenerated  Mon Jul 28 21:25:09 CST 2014
	 */
	public Long getKindId() {
		return kindId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attr_group.kind_id
	 * @param kindId  the value for attr_group.kind_id
	 * @mbggenerated  Mon Jul 28 21:25:09 CST 2014
	 */
	public void setKindId(Long kindId) {
		this.kindId = kindId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attr_group.group_name
	 * @return  the value of attr_group.group_name
	 * @mbggenerated  Mon Jul 28 21:25:09 CST 2014
	 */
	public String getGroupName() {
		return groupName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attr_group.group_name
	 * @param groupName  the value for attr_group.group_name
	 * @mbggenerated  Mon Jul 28 21:25:09 CST 2014
	 */
	public void setGroupName(String groupName) {
		this.groupName = groupName == null ? null : groupName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attr_group.status
	 * @return  the value of attr_group.status
	 * @mbggenerated  Mon Jul 28 21:25:09 CST 2014
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attr_group.status
	 * @param status  the value for attr_group.status
	 * @mbggenerated  Mon Jul 28 21:25:09 CST 2014
	 */
	public void setStatus(Short status) {
		this.status = status;
	}
}