package com.mission.shop.product.dao.model;

import java.io.Serializable;
import java.util.Date;

public class Attribute implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attribute.attr_id
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	private Long attrId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attribute.attr_group_id
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	private Long attrGroupId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attribute.kind_id
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	private Long kindId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attribute.attr_name
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	private String attrName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attribute.attr_values
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	private String attrValues;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attribute.attr_type
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	private Short attrType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attribute.create_time
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attribute.update_time
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table attribute
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attribute.attr_id
	 * @return  the value of attribute.attr_id
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	public Long getAttrId() {
		return attrId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attribute.attr_id
	 * @param attrId  the value for attribute.attr_id
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	public void setAttrId(Long attrId) {
		this.attrId = attrId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attribute.attr_group_id
	 * @return  the value of attribute.attr_group_id
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	public Long getAttrGroupId() {
		return attrGroupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attribute.attr_group_id
	 * @param attrGroupId  the value for attribute.attr_group_id
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	public void setAttrGroupId(Long attrGroupId) {
		this.attrGroupId = attrGroupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attribute.kind_id
	 * @return  the value of attribute.kind_id
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	public Long getKindId() {
		return kindId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attribute.kind_id
	 * @param kindId  the value for attribute.kind_id
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	public void setKindId(Long kindId) {
		this.kindId = kindId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attribute.attr_name
	 * @return  the value of attribute.attr_name
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	public String getAttrName() {
		return attrName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attribute.attr_name
	 * @param attrName  the value for attribute.attr_name
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	public void setAttrName(String attrName) {
		this.attrName = attrName == null ? null : attrName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attribute.attr_values
	 * @return  the value of attribute.attr_values
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	public String getAttrValues() {
		return attrValues;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attribute.attr_values
	 * @param attrValues  the value for attribute.attr_values
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	public void setAttrValues(String attrValues) {
		this.attrValues = attrValues == null ? null : attrValues.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attribute.attr_type
	 * @return  the value of attribute.attr_type
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	public Short getAttrType() {
		return attrType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attribute.attr_type
	 * @param attrType  the value for attribute.attr_type
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	public void setAttrType(Short attrType) {
		this.attrType = attrType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attribute.create_time
	 * @return  the value of attribute.create_time
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attribute.create_time
	 * @param createTime  the value for attribute.create_time
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attribute.update_time
	 * @return  the value of attribute.update_time
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attribute.update_time
	 * @param updateTime  the value for attribute.update_time
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}