package com.mission.shop.product.dao.model;

import java.io.Serializable;
import java.util.Date;

public class PackingList implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column packing_list.id
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column packing_list.product_id
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	private Long productId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column packing_list.goods_name
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	private String goodsName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column packing_list.num
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	private Short num;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column packing_list.status
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column packing_list.create_time
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column packing_list.update_time
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table packing_list
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column packing_list.id
	 * @return  the value of packing_list.id
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column packing_list.id
	 * @param id  the value for packing_list.id
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column packing_list.product_id
	 * @return  the value of packing_list.product_id
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	public Long getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column packing_list.product_id
	 * @param productId  the value for packing_list.product_id
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	public void setProductId(Long productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column packing_list.goods_name
	 * @return  the value of packing_list.goods_name
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	public String getGoodsName() {
		return goodsName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column packing_list.goods_name
	 * @param goodsName  the value for packing_list.goods_name
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	public void setGoodsName(String goodsName) {
		this.goodsName = goodsName == null ? null : goodsName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column packing_list.num
	 * @return  the value of packing_list.num
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	public Short getNum() {
		return num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column packing_list.num
	 * @param num  the value for packing_list.num
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	public void setNum(Short num) {
		this.num = num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column packing_list.status
	 * @return  the value of packing_list.status
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column packing_list.status
	 * @param status  the value for packing_list.status
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column packing_list.create_time
	 * @return  the value of packing_list.create_time
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column packing_list.create_time
	 * @param createTime  the value for packing_list.create_time
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column packing_list.update_time
	 * @return  the value of packing_list.update_time
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column packing_list.update_time
	 * @param updateTime  the value for packing_list.update_time
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}