package com.mission.shop.product.dao.model;

import java.io.Serializable;
import java.util.Date;

public class Product implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.product_id
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	private Long productId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.kind_id
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	private Long kindId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.shop_id
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	private Long shopId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.shop_name
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	private String shopName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.product_name
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	private String productName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.product_title
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	private String productTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.brand_id
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	private Long brandId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.brand_name
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	private String brandName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.view_num
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	private Long viewNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.status
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.pay_type
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	private Integer payType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.delevery_amount
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	private Integer deleveryAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.min_price
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	private Integer minPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.max_price
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	private Integer maxPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.pic_url
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	private String picUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.comment_times
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	private Integer commentTimes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.score
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	private Integer score;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.create_time
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.update_time
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.sales
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	private Integer sales;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table product
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.product_id
	 * @return  the value of product.product_id
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	public Long getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.product_id
	 * @param productId  the value for product.product_id
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	public void setProductId(Long productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.kind_id
	 * @return  the value of product.kind_id
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	public Long getKindId() {
		return kindId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.kind_id
	 * @param kindId  the value for product.kind_id
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	public void setKindId(Long kindId) {
		this.kindId = kindId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.shop_id
	 * @return  the value of product.shop_id
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	public Long getShopId() {
		return shopId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.shop_id
	 * @param shopId  the value for product.shop_id
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	public void setShopId(Long shopId) {
		this.shopId = shopId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.shop_name
	 * @return  the value of product.shop_name
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	public String getShopName() {
		return shopName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.shop_name
	 * @param shopName  the value for product.shop_name
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	public void setShopName(String shopName) {
		this.shopName = shopName == null ? null : shopName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.product_name
	 * @return  the value of product.product_name
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	public String getProductName() {
		return productName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.product_name
	 * @param productName  the value for product.product_name
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	public void setProductName(String productName) {
		this.productName = productName == null ? null : productName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.product_title
	 * @return  the value of product.product_title
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	public String getProductTitle() {
		return productTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.product_title
	 * @param productTitle  the value for product.product_title
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	public void setProductTitle(String productTitle) {
		this.productTitle = productTitle == null ? null : productTitle.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.brand_id
	 * @return  the value of product.brand_id
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	public Long getBrandId() {
		return brandId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.brand_id
	 * @param brandId  the value for product.brand_id
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	public void setBrandId(Long brandId) {
		this.brandId = brandId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.brand_name
	 * @return  the value of product.brand_name
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	public String getBrandName() {
		return brandName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.brand_name
	 * @param brandName  the value for product.brand_name
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	public void setBrandName(String brandName) {
		this.brandName = brandName == null ? null : brandName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.view_num
	 * @return  the value of product.view_num
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	public Long getViewNum() {
		return viewNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.view_num
	 * @param viewNum  the value for product.view_num
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	public void setViewNum(Long viewNum) {
		this.viewNum = viewNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.status
	 * @return  the value of product.status
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.status
	 * @param status  the value for product.status
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.pay_type
	 * @return  the value of product.pay_type
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	public Integer getPayType() {
		return payType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.pay_type
	 * @param payType  the value for product.pay_type
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	public void setPayType(Integer payType) {
		this.payType = payType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.delevery_amount
	 * @return  the value of product.delevery_amount
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	public Integer getDeleveryAmount() {
		return deleveryAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.delevery_amount
	 * @param deleveryAmount  the value for product.delevery_amount
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	public void setDeleveryAmount(Integer deleveryAmount) {
		this.deleveryAmount = deleveryAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.min_price
	 * @return  the value of product.min_price
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	public Integer getMinPrice() {
		return minPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.min_price
	 * @param minPrice  the value for product.min_price
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	public void setMinPrice(Integer minPrice) {
		this.minPrice = minPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.max_price
	 * @return  the value of product.max_price
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	public Integer getMaxPrice() {
		return maxPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.max_price
	 * @param maxPrice  the value for product.max_price
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	public void setMaxPrice(Integer maxPrice) {
		this.maxPrice = maxPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.pic_url
	 * @return  the value of product.pic_url
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	public String getPicUrl() {
		return picUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.pic_url
	 * @param picUrl  the value for product.pic_url
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	public void setPicUrl(String picUrl) {
		this.picUrl = picUrl == null ? null : picUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.comment_times
	 * @return  the value of product.comment_times
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	public Integer getCommentTimes() {
		return commentTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.comment_times
	 * @param commentTimes  the value for product.comment_times
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	public void setCommentTimes(Integer commentTimes) {
		this.commentTimes = commentTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.score
	 * @return  the value of product.score
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	public Integer getScore() {
		return score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.score
	 * @param score  the value for product.score
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	public void setScore(Integer score) {
		this.score = score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.create_time
	 * @return  the value of product.create_time
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.create_time
	 * @param createTime  the value for product.create_time
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.update_time
	 * @return  the value of product.update_time
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.update_time
	 * @param updateTime  the value for product.update_time
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.sales
	 * @return  the value of product.sales
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	public Integer getSales() {
		return sales;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.sales
	 * @param sales  the value for product.sales
	 * @mbggenerated  Sat Jul 12 23:07:03 CST 2014
	 */
	public void setSales(Integer sales) {
		this.sales = sales;
	}
}