package com.mission.shop.product.dao.model;

import java.util.ArrayList;
import java.util.List;

public class ProductPicExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table product_pic
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table product_pic
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table product_pic
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_pic
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	public ProductPicExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_pic
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_pic
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_pic
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_pic
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_pic
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_pic
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_pic
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_pic
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_pic
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_pic
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table product_pic
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andProductPicIdIsNull() {
			addCriterion("product_pic_id is null");
			return (Criteria) this;
		}

		public Criteria andProductPicIdIsNotNull() {
			addCriterion("product_pic_id is not null");
			return (Criteria) this;
		}

		public Criteria andProductPicIdEqualTo(Long value) {
			addCriterion("product_pic_id =", value, "productPicId");
			return (Criteria) this;
		}

		public Criteria andProductPicIdNotEqualTo(Long value) {
			addCriterion("product_pic_id <>", value, "productPicId");
			return (Criteria) this;
		}

		public Criteria andProductPicIdGreaterThan(Long value) {
			addCriterion("product_pic_id >", value, "productPicId");
			return (Criteria) this;
		}

		public Criteria andProductPicIdGreaterThanOrEqualTo(Long value) {
			addCriterion("product_pic_id >=", value, "productPicId");
			return (Criteria) this;
		}

		public Criteria andProductPicIdLessThan(Long value) {
			addCriterion("product_pic_id <", value, "productPicId");
			return (Criteria) this;
		}

		public Criteria andProductPicIdLessThanOrEqualTo(Long value) {
			addCriterion("product_pic_id <=", value, "productPicId");
			return (Criteria) this;
		}

		public Criteria andProductPicIdIn(List<Long> values) {
			addCriterion("product_pic_id in", values, "productPicId");
			return (Criteria) this;
		}

		public Criteria andProductPicIdNotIn(List<Long> values) {
			addCriterion("product_pic_id not in", values, "productPicId");
			return (Criteria) this;
		}

		public Criteria andProductPicIdBetween(Long value1, Long value2) {
			addCriterion("product_pic_id between", value1, value2,
					"productPicId");
			return (Criteria) this;
		}

		public Criteria andProductPicIdNotBetween(Long value1, Long value2) {
			addCriterion("product_pic_id not between", value1, value2,
					"productPicId");
			return (Criteria) this;
		}

		public Criteria andProductIdIsNull() {
			addCriterion("product_id is null");
			return (Criteria) this;
		}

		public Criteria andProductIdIsNotNull() {
			addCriterion("product_id is not null");
			return (Criteria) this;
		}

		public Criteria andProductIdEqualTo(Long value) {
			addCriterion("product_id =", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdNotEqualTo(Long value) {
			addCriterion("product_id <>", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdGreaterThan(Long value) {
			addCriterion("product_id >", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdGreaterThanOrEqualTo(Long value) {
			addCriterion("product_id >=", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdLessThan(Long value) {
			addCriterion("product_id <", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdLessThanOrEqualTo(Long value) {
			addCriterion("product_id <=", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdIn(List<Long> values) {
			addCriterion("product_id in", values, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdNotIn(List<Long> values) {
			addCriterion("product_id not in", values, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdBetween(Long value1, Long value2) {
			addCriterion("product_id between", value1, value2, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdNotBetween(Long value1, Long value2) {
			addCriterion("product_id not between", value1, value2, "productId");
			return (Criteria) this;
		}

		public Criteria andUrlIsNull() {
			addCriterion("url is null");
			return (Criteria) this;
		}

		public Criteria andUrlIsNotNull() {
			addCriterion("url is not null");
			return (Criteria) this;
		}

		public Criteria andUrlEqualTo(String value) {
			addCriterion("url =", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlNotEqualTo(String value) {
			addCriterion("url <>", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlGreaterThan(String value) {
			addCriterion("url >", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlGreaterThanOrEqualTo(String value) {
			addCriterion("url >=", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlLessThan(String value) {
			addCriterion("url <", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlLessThanOrEqualTo(String value) {
			addCriterion("url <=", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlLike(String value) {
			addCriterion("url like", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlNotLike(String value) {
			addCriterion("url not like", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlIn(List<String> values) {
			addCriterion("url in", values, "url");
			return (Criteria) this;
		}

		public Criteria andUrlNotIn(List<String> values) {
			addCriterion("url not in", values, "url");
			return (Criteria) this;
		}

		public Criteria andUrlBetween(String value1, String value2) {
			addCriterion("url between", value1, value2, "url");
			return (Criteria) this;
		}

		public Criteria andUrlNotBetween(String value1, String value2) {
			addCriterion("url not between", value1, value2, "url");
			return (Criteria) this;
		}

		public Criteria andImageNameIsNull() {
			addCriterion("image_name is null");
			return (Criteria) this;
		}

		public Criteria andImageNameIsNotNull() {
			addCriterion("image_name is not null");
			return (Criteria) this;
		}

		public Criteria andImageNameEqualTo(String value) {
			addCriterion("image_name =", value, "imageName");
			return (Criteria) this;
		}

		public Criteria andImageNameNotEqualTo(String value) {
			addCriterion("image_name <>", value, "imageName");
			return (Criteria) this;
		}

		public Criteria andImageNameGreaterThan(String value) {
			addCriterion("image_name >", value, "imageName");
			return (Criteria) this;
		}

		public Criteria andImageNameGreaterThanOrEqualTo(String value) {
			addCriterion("image_name >=", value, "imageName");
			return (Criteria) this;
		}

		public Criteria andImageNameLessThan(String value) {
			addCriterion("image_name <", value, "imageName");
			return (Criteria) this;
		}

		public Criteria andImageNameLessThanOrEqualTo(String value) {
			addCriterion("image_name <=", value, "imageName");
			return (Criteria) this;
		}

		public Criteria andImageNameLike(String value) {
			addCriterion("image_name like", value, "imageName");
			return (Criteria) this;
		}

		public Criteria andImageNameNotLike(String value) {
			addCriterion("image_name not like", value, "imageName");
			return (Criteria) this;
		}

		public Criteria andImageNameIn(List<String> values) {
			addCriterion("image_name in", values, "imageName");
			return (Criteria) this;
		}

		public Criteria andImageNameNotIn(List<String> values) {
			addCriterion("image_name not in", values, "imageName");
			return (Criteria) this;
		}

		public Criteria andImageNameBetween(String value1, String value2) {
			addCriterion("image_name between", value1, value2, "imageName");
			return (Criteria) this;
		}

		public Criteria andImageNameNotBetween(String value1, String value2) {
			addCriterion("image_name not between", value1, value2, "imageName");
			return (Criteria) this;
		}

		public Criteria andPostFixIsNull() {
			addCriterion("post_fix is null");
			return (Criteria) this;
		}

		public Criteria andPostFixIsNotNull() {
			addCriterion("post_fix is not null");
			return (Criteria) this;
		}

		public Criteria andPostFixEqualTo(String value) {
			addCriterion("post_fix =", value, "postFix");
			return (Criteria) this;
		}

		public Criteria andPostFixNotEqualTo(String value) {
			addCriterion("post_fix <>", value, "postFix");
			return (Criteria) this;
		}

		public Criteria andPostFixGreaterThan(String value) {
			addCriterion("post_fix >", value, "postFix");
			return (Criteria) this;
		}

		public Criteria andPostFixGreaterThanOrEqualTo(String value) {
			addCriterion("post_fix >=", value, "postFix");
			return (Criteria) this;
		}

		public Criteria andPostFixLessThan(String value) {
			addCriterion("post_fix <", value, "postFix");
			return (Criteria) this;
		}

		public Criteria andPostFixLessThanOrEqualTo(String value) {
			addCriterion("post_fix <=", value, "postFix");
			return (Criteria) this;
		}

		public Criteria andPostFixLike(String value) {
			addCriterion("post_fix like", value, "postFix");
			return (Criteria) this;
		}

		public Criteria andPostFixNotLike(String value) {
			addCriterion("post_fix not like", value, "postFix");
			return (Criteria) this;
		}

		public Criteria andPostFixIn(List<String> values) {
			addCriterion("post_fix in", values, "postFix");
			return (Criteria) this;
		}

		public Criteria andPostFixNotIn(List<String> values) {
			addCriterion("post_fix not in", values, "postFix");
			return (Criteria) this;
		}

		public Criteria andPostFixBetween(String value1, String value2) {
			addCriterion("post_fix between", value1, value2, "postFix");
			return (Criteria) this;
		}

		public Criteria andPostFixNotBetween(String value1, String value2) {
			addCriterion("post_fix not between", value1, value2, "postFix");
			return (Criteria) this;
		}

		public Criteria andBriefNameIsNull() {
			addCriterion("brief_name is null");
			return (Criteria) this;
		}

		public Criteria andBriefNameIsNotNull() {
			addCriterion("brief_name is not null");
			return (Criteria) this;
		}

		public Criteria andBriefNameEqualTo(String value) {
			addCriterion("brief_name =", value, "briefName");
			return (Criteria) this;
		}

		public Criteria andBriefNameNotEqualTo(String value) {
			addCriterion("brief_name <>", value, "briefName");
			return (Criteria) this;
		}

		public Criteria andBriefNameGreaterThan(String value) {
			addCriterion("brief_name >", value, "briefName");
			return (Criteria) this;
		}

		public Criteria andBriefNameGreaterThanOrEqualTo(String value) {
			addCriterion("brief_name >=", value, "briefName");
			return (Criteria) this;
		}

		public Criteria andBriefNameLessThan(String value) {
			addCriterion("brief_name <", value, "briefName");
			return (Criteria) this;
		}

		public Criteria andBriefNameLessThanOrEqualTo(String value) {
			addCriterion("brief_name <=", value, "briefName");
			return (Criteria) this;
		}

		public Criteria andBriefNameLike(String value) {
			addCriterion("brief_name like", value, "briefName");
			return (Criteria) this;
		}

		public Criteria andBriefNameNotLike(String value) {
			addCriterion("brief_name not like", value, "briefName");
			return (Criteria) this;
		}

		public Criteria andBriefNameIn(List<String> values) {
			addCriterion("brief_name in", values, "briefName");
			return (Criteria) this;
		}

		public Criteria andBriefNameNotIn(List<String> values) {
			addCriterion("brief_name not in", values, "briefName");
			return (Criteria) this;
		}

		public Criteria andBriefNameBetween(String value1, String value2) {
			addCriterion("brief_name between", value1, value2, "briefName");
			return (Criteria) this;
		}

		public Criteria andBriefNameNotBetween(String value1, String value2) {
			addCriterion("brief_name not between", value1, value2, "briefName");
			return (Criteria) this;
		}

		public Criteria andUseTypeIsNull() {
			addCriterion("use_type is null");
			return (Criteria) this;
		}

		public Criteria andUseTypeIsNotNull() {
			addCriterion("use_type is not null");
			return (Criteria) this;
		}

		public Criteria andUseTypeEqualTo(Short value) {
			addCriterion("use_type =", value, "useType");
			return (Criteria) this;
		}

		public Criteria andUseTypeNotEqualTo(Short value) {
			addCriterion("use_type <>", value, "useType");
			return (Criteria) this;
		}

		public Criteria andUseTypeGreaterThan(Short value) {
			addCriterion("use_type >", value, "useType");
			return (Criteria) this;
		}

		public Criteria andUseTypeGreaterThanOrEqualTo(Short value) {
			addCriterion("use_type >=", value, "useType");
			return (Criteria) this;
		}

		public Criteria andUseTypeLessThan(Short value) {
			addCriterion("use_type <", value, "useType");
			return (Criteria) this;
		}

		public Criteria andUseTypeLessThanOrEqualTo(Short value) {
			addCriterion("use_type <=", value, "useType");
			return (Criteria) this;
		}

		public Criteria andUseTypeIn(List<Short> values) {
			addCriterion("use_type in", values, "useType");
			return (Criteria) this;
		}

		public Criteria andUseTypeNotIn(List<Short> values) {
			addCriterion("use_type not in", values, "useType");
			return (Criteria) this;
		}

		public Criteria andUseTypeBetween(Short value1, Short value2) {
			addCriterion("use_type between", value1, value2, "useType");
			return (Criteria) this;
		}

		public Criteria andUseTypeNotBetween(Short value1, Short value2) {
			addCriterion("use_type not between", value1, value2, "useType");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Short value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Short value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Short value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Short value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Short value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Short value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Short> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Short> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Short value1, Short value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Short value1, Short value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table product_pic
	 * @mbggenerated  Wed Aug 20 14:11:54 CST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product_pic
     *
     * @mbggenerated do_not_delete_during_merge Tue Jul 15 20:06:31 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}