package com.mission.shop.product.dao.model;

import java.io.Serializable;

public class ProductPic implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_pic.product_pic_id
	 * @mbggenerated  Wed Jul 16 14:05:26 CST 2014
	 */
	private Long productPicId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_pic.product_id
	 * @mbggenerated  Wed Jul 16 14:05:26 CST 2014
	 */
	private Long productId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_pic.url
	 * @mbggenerated  Wed Jul 16 14:05:26 CST 2014
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_pic.image_name
	 * @mbggenerated  Wed Jul 16 14:05:26 CST 2014
	 */
	private String imageName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_pic.post_fix
	 * @mbggenerated  Wed Jul 16 14:05:26 CST 2014
	 */
	private String postFix;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_pic.brief_name
	 * @mbggenerated  Wed Jul 16 14:05:26 CST 2014
	 */
	private String briefName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_pic.use_type
	 * @mbggenerated  Wed Jul 16 14:05:26 CST 2014
	 */
	private Short useType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_pic.status
	 * @mbggenerated  Wed Jul 16 14:05:26 CST 2014
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table product_pic
	 * @mbggenerated  Wed Jul 16 14:05:26 CST 2014
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_pic.product_pic_id
	 * @return  the value of product_pic.product_pic_id
	 * @mbggenerated  Wed Jul 16 14:05:26 CST 2014
	 */
	public Long getProductPicId() {
		return productPicId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_pic.product_pic_id
	 * @param productPicId  the value for product_pic.product_pic_id
	 * @mbggenerated  Wed Jul 16 14:05:26 CST 2014
	 */
	public void setProductPicId(Long productPicId) {
		this.productPicId = productPicId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_pic.product_id
	 * @return  the value of product_pic.product_id
	 * @mbggenerated  Wed Jul 16 14:05:26 CST 2014
	 */
	public Long getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_pic.product_id
	 * @param productId  the value for product_pic.product_id
	 * @mbggenerated  Wed Jul 16 14:05:26 CST 2014
	 */
	public void setProductId(Long productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_pic.url
	 * @return  the value of product_pic.url
	 * @mbggenerated  Wed Jul 16 14:05:26 CST 2014
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_pic.url
	 * @param url  the value for product_pic.url
	 * @mbggenerated  Wed Jul 16 14:05:26 CST 2014
	 */
	public void setUrl(String url) {
		this.url = url == null ? null : url.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_pic.image_name
	 * @return  the value of product_pic.image_name
	 * @mbggenerated  Wed Jul 16 14:05:26 CST 2014
	 */
	public String getImageName() {
		return imageName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_pic.image_name
	 * @param imageName  the value for product_pic.image_name
	 * @mbggenerated  Wed Jul 16 14:05:26 CST 2014
	 */
	public void setImageName(String imageName) {
		this.imageName = imageName == null ? null : imageName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_pic.post_fix
	 * @return  the value of product_pic.post_fix
	 * @mbggenerated  Wed Jul 16 14:05:26 CST 2014
	 */
	public String getPostFix() {
		return postFix;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_pic.post_fix
	 * @param postFix  the value for product_pic.post_fix
	 * @mbggenerated  Wed Jul 16 14:05:26 CST 2014
	 */
	public void setPostFix(String postFix) {
		this.postFix = postFix == null ? null : postFix.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_pic.brief_name
	 * @return  the value of product_pic.brief_name
	 * @mbggenerated  Wed Jul 16 14:05:26 CST 2014
	 */
	public String getBriefName() {
		return briefName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_pic.brief_name
	 * @param briefName  the value for product_pic.brief_name
	 * @mbggenerated  Wed Jul 16 14:05:26 CST 2014
	 */
	public void setBriefName(String briefName) {
		this.briefName = briefName == null ? null : briefName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_pic.use_type
	 * @return  the value of product_pic.use_type
	 * @mbggenerated  Wed Jul 16 14:05:26 CST 2014
	 */
	public Short getUseType() {
		return useType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_pic.use_type
	 * @param useType  the value for product_pic.use_type
	 * @mbggenerated  Wed Jul 16 14:05:26 CST 2014
	 */
	public void setUseType(Short useType) {
		this.useType = useType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_pic.status
	 * @return  the value of product_pic.status
	 * @mbggenerated  Wed Jul 16 14:05:26 CST 2014
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_pic.status
	 * @param status  the value for product_pic.status
	 * @mbggenerated  Wed Jul 16 14:05:26 CST 2014
	 */
	public void setStatus(Short status) {
		this.status = status;
	}
}