package com.mission.shop.product.dao.model;

import java.io.Serializable;
import java.util.Date;

public class ProductAttr implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_attr.id
	 * @mbggenerated  Thu Jul 10 21:41:41 CST 2014
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_attr.product_id
	 * @mbggenerated  Thu Jul 10 21:41:41 CST 2014
	 */
	private Long productId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_attr.attr_group_id
	 * @mbggenerated  Thu Jul 10 21:41:41 CST 2014
	 */
	private Long attrGroupId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_attr.attr_name
	 * @mbggenerated  Thu Jul 10 21:41:41 CST 2014
	 */
	private String attrName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_attr.attr_value
	 * @mbggenerated  Thu Jul 10 21:41:41 CST 2014
	 */
	private String attrValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_attr.sort_order
	 * @mbggenerated  Thu Jul 10 21:41:41 CST 2014
	 */
	private Integer sortOrder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_attr.attr_type
	 * @mbggenerated  Thu Jul 10 21:41:41 CST 2014
	 */
	private Integer attrType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table product_attr
	 * @mbggenerated  Thu Jul 10 21:41:41 CST 2014
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_attr.id
	 * @return  the value of product_attr.id
	 * @mbggenerated  Thu Jul 10 21:41:41 CST 2014
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_attr.id
	 * @param id  the value for product_attr.id
	 * @mbggenerated  Thu Jul 10 21:41:41 CST 2014
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_attr.product_id
	 * @return  the value of product_attr.product_id
	 * @mbggenerated  Thu Jul 10 21:41:41 CST 2014
	 */
	public Long getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_attr.product_id
	 * @param productId  the value for product_attr.product_id
	 * @mbggenerated  Thu Jul 10 21:41:41 CST 2014
	 */
	public void setProductId(Long productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_attr.attr_group_id
	 * @return  the value of product_attr.attr_group_id
	 * @mbggenerated  Thu Jul 10 21:41:41 CST 2014
	 */
	public Long getAttrGroupId() {
		return attrGroupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_attr.attr_group_id
	 * @param attrGroupId  the value for product_attr.attr_group_id
	 * @mbggenerated  Thu Jul 10 21:41:41 CST 2014
	 */
	public void setAttrGroupId(Long attrGroupId) {
		this.attrGroupId = attrGroupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_attr.attr_name
	 * @return  the value of product_attr.attr_name
	 * @mbggenerated  Thu Jul 10 21:41:41 CST 2014
	 */
	public String getAttrName() {
		return attrName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_attr.attr_name
	 * @param attrName  the value for product_attr.attr_name
	 * @mbggenerated  Thu Jul 10 21:41:41 CST 2014
	 */
	public void setAttrName(String attrName) {
		this.attrName = attrName == null ? null : attrName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_attr.attr_value
	 * @return  the value of product_attr.attr_value
	 * @mbggenerated  Thu Jul 10 21:41:41 CST 2014
	 */
	public String getAttrValue() {
		return attrValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_attr.attr_value
	 * @param attrValue  the value for product_attr.attr_value
	 * @mbggenerated  Thu Jul 10 21:41:41 CST 2014
	 */
	public void setAttrValue(String attrValue) {
		this.attrValue = attrValue == null ? null : attrValue.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_attr.sort_order
	 * @return  the value of product_attr.sort_order
	 * @mbggenerated  Thu Jul 10 21:41:41 CST 2014
	 */
	public Integer getSortOrder() {
		return sortOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_attr.sort_order
	 * @param sortOrder  the value for product_attr.sort_order
	 * @mbggenerated  Thu Jul 10 21:41:41 CST 2014
	 */
	public void setSortOrder(Integer sortOrder) {
		this.sortOrder = sortOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_attr.attr_type
	 * @return  the value of product_attr.attr_type
	 * @mbggenerated  Thu Jul 10 21:41:41 CST 2014
	 */
	public Integer getAttrType() {
		return attrType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_attr.attr_type
	 * @param attrType  the value for product_attr.attr_type
	 * @mbggenerated  Thu Jul 10 21:41:41 CST 2014
	 */
	public void setAttrType(Integer attrType) {
		this.attrType = attrType;
	}
}