package com.mission.shop.product.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProductExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table product
	 * @mbggenerated  Mon Nov 24 16:04:02 CST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table product
	 * @mbggenerated  Mon Nov 24 16:04:02 CST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table product
	 * @mbggenerated  Mon Nov 24 16:04:02 CST 2014
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Mon Nov 24 16:04:02 CST 2014
	 */
	public ProductExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Mon Nov 24 16:04:02 CST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Mon Nov 24 16:04:02 CST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Mon Nov 24 16:04:02 CST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Mon Nov 24 16:04:02 CST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Mon Nov 24 16:04:02 CST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Mon Nov 24 16:04:02 CST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Mon Nov 24 16:04:02 CST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Mon Nov 24 16:04:02 CST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Mon Nov 24 16:04:02 CST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Mon Nov 24 16:04:02 CST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table product
	 * @mbggenerated  Mon Nov 24 16:04:02 CST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andProductIdIsNull() {
			addCriterion("product_id is null");
			return (Criteria) this;
		}

		public Criteria andProductIdIsNotNull() {
			addCriterion("product_id is not null");
			return (Criteria) this;
		}

		public Criteria andProductIdEqualTo(Long value) {
			addCriterion("product_id =", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdNotEqualTo(Long value) {
			addCriterion("product_id <>", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdGreaterThan(Long value) {
			addCriterion("product_id >", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdGreaterThanOrEqualTo(Long value) {
			addCriterion("product_id >=", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdLessThan(Long value) {
			addCriterion("product_id <", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdLessThanOrEqualTo(Long value) {
			addCriterion("product_id <=", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdIn(List<Long> values) {
			addCriterion("product_id in", values, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdNotIn(List<Long> values) {
			addCriterion("product_id not in", values, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdBetween(Long value1, Long value2) {
			addCriterion("product_id between", value1, value2, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdNotBetween(Long value1, Long value2) {
			addCriterion("product_id not between", value1, value2, "productId");
			return (Criteria) this;
		}

		public Criteria andKindIdIsNull() {
			addCriterion("kind_id is null");
			return (Criteria) this;
		}

		public Criteria andKindIdIsNotNull() {
			addCriterion("kind_id is not null");
			return (Criteria) this;
		}

		public Criteria andKindIdEqualTo(Long value) {
			addCriterion("kind_id =", value, "kindId");
			return (Criteria) this;
		}

		public Criteria andKindIdNotEqualTo(Long value) {
			addCriterion("kind_id <>", value, "kindId");
			return (Criteria) this;
		}

		public Criteria andKindIdGreaterThan(Long value) {
			addCriterion("kind_id >", value, "kindId");
			return (Criteria) this;
		}

		public Criteria andKindIdGreaterThanOrEqualTo(Long value) {
			addCriterion("kind_id >=", value, "kindId");
			return (Criteria) this;
		}

		public Criteria andKindIdLessThan(Long value) {
			addCriterion("kind_id <", value, "kindId");
			return (Criteria) this;
		}

		public Criteria andKindIdLessThanOrEqualTo(Long value) {
			addCriterion("kind_id <=", value, "kindId");
			return (Criteria) this;
		}

		public Criteria andKindIdIn(List<Long> values) {
			addCriterion("kind_id in", values, "kindId");
			return (Criteria) this;
		}

		public Criteria andKindIdNotIn(List<Long> values) {
			addCriterion("kind_id not in", values, "kindId");
			return (Criteria) this;
		}

		public Criteria andKindIdBetween(Long value1, Long value2) {
			addCriterion("kind_id between", value1, value2, "kindId");
			return (Criteria) this;
		}

		public Criteria andKindIdNotBetween(Long value1, Long value2) {
			addCriterion("kind_id not between", value1, value2, "kindId");
			return (Criteria) this;
		}

		public Criteria andShopIdIsNull() {
			addCriterion("shop_id is null");
			return (Criteria) this;
		}

		public Criteria andShopIdIsNotNull() {
			addCriterion("shop_id is not null");
			return (Criteria) this;
		}

		public Criteria andShopIdEqualTo(Long value) {
			addCriterion("shop_id =", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdNotEqualTo(Long value) {
			addCriterion("shop_id <>", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdGreaterThan(Long value) {
			addCriterion("shop_id >", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdGreaterThanOrEqualTo(Long value) {
			addCriterion("shop_id >=", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdLessThan(Long value) {
			addCriterion("shop_id <", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdLessThanOrEqualTo(Long value) {
			addCriterion("shop_id <=", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdIn(List<Long> values) {
			addCriterion("shop_id in", values, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdNotIn(List<Long> values) {
			addCriterion("shop_id not in", values, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdBetween(Long value1, Long value2) {
			addCriterion("shop_id between", value1, value2, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdNotBetween(Long value1, Long value2) {
			addCriterion("shop_id not between", value1, value2, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopNameIsNull() {
			addCriterion("shop_name is null");
			return (Criteria) this;
		}

		public Criteria andShopNameIsNotNull() {
			addCriterion("shop_name is not null");
			return (Criteria) this;
		}

		public Criteria andShopNameEqualTo(String value) {
			addCriterion("shop_name =", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameNotEqualTo(String value) {
			addCriterion("shop_name <>", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameGreaterThan(String value) {
			addCriterion("shop_name >", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameGreaterThanOrEqualTo(String value) {
			addCriterion("shop_name >=", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameLessThan(String value) {
			addCriterion("shop_name <", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameLessThanOrEqualTo(String value) {
			addCriterion("shop_name <=", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameLike(String value) {
			addCriterion("shop_name like", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameNotLike(String value) {
			addCriterion("shop_name not like", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameIn(List<String> values) {
			addCriterion("shop_name in", values, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameNotIn(List<String> values) {
			addCriterion("shop_name not in", values, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameBetween(String value1, String value2) {
			addCriterion("shop_name between", value1, value2, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameNotBetween(String value1, String value2) {
			addCriterion("shop_name not between", value1, value2, "shopName");
			return (Criteria) this;
		}

		public Criteria andSellerIdIsNull() {
			addCriterion("seller_id is null");
			return (Criteria) this;
		}

		public Criteria andSellerIdIsNotNull() {
			addCriterion("seller_id is not null");
			return (Criteria) this;
		}

		public Criteria andSellerIdEqualTo(Long value) {
			addCriterion("seller_id =", value, "sellerId");
			return (Criteria) this;
		}

		public Criteria andSellerIdNotEqualTo(Long value) {
			addCriterion("seller_id <>", value, "sellerId");
			return (Criteria) this;
		}

		public Criteria andSellerIdGreaterThan(Long value) {
			addCriterion("seller_id >", value, "sellerId");
			return (Criteria) this;
		}

		public Criteria andSellerIdGreaterThanOrEqualTo(Long value) {
			addCriterion("seller_id >=", value, "sellerId");
			return (Criteria) this;
		}

		public Criteria andSellerIdLessThan(Long value) {
			addCriterion("seller_id <", value, "sellerId");
			return (Criteria) this;
		}

		public Criteria andSellerIdLessThanOrEqualTo(Long value) {
			addCriterion("seller_id <=", value, "sellerId");
			return (Criteria) this;
		}

		public Criteria andSellerIdIn(List<Long> values) {
			addCriterion("seller_id in", values, "sellerId");
			return (Criteria) this;
		}

		public Criteria andSellerIdNotIn(List<Long> values) {
			addCriterion("seller_id not in", values, "sellerId");
			return (Criteria) this;
		}

		public Criteria andSellerIdBetween(Long value1, Long value2) {
			addCriterion("seller_id between", value1, value2, "sellerId");
			return (Criteria) this;
		}

		public Criteria andSellerIdNotBetween(Long value1, Long value2) {
			addCriterion("seller_id not between", value1, value2, "sellerId");
			return (Criteria) this;
		}

		public Criteria andSellerUserNameIsNull() {
			addCriterion("seller_user_name is null");
			return (Criteria) this;
		}

		public Criteria andSellerUserNameIsNotNull() {
			addCriterion("seller_user_name is not null");
			return (Criteria) this;
		}

		public Criteria andSellerUserNameEqualTo(String value) {
			addCriterion("seller_user_name =", value, "sellerUserName");
			return (Criteria) this;
		}

		public Criteria andSellerUserNameNotEqualTo(String value) {
			addCriterion("seller_user_name <>", value, "sellerUserName");
			return (Criteria) this;
		}

		public Criteria andSellerUserNameGreaterThan(String value) {
			addCriterion("seller_user_name >", value, "sellerUserName");
			return (Criteria) this;
		}

		public Criteria andSellerUserNameGreaterThanOrEqualTo(String value) {
			addCriterion("seller_user_name >=", value, "sellerUserName");
			return (Criteria) this;
		}

		public Criteria andSellerUserNameLessThan(String value) {
			addCriterion("seller_user_name <", value, "sellerUserName");
			return (Criteria) this;
		}

		public Criteria andSellerUserNameLessThanOrEqualTo(String value) {
			addCriterion("seller_user_name <=", value, "sellerUserName");
			return (Criteria) this;
		}

		public Criteria andSellerUserNameLike(String value) {
			addCriterion("seller_user_name like", value, "sellerUserName");
			return (Criteria) this;
		}

		public Criteria andSellerUserNameNotLike(String value) {
			addCriterion("seller_user_name not like", value, "sellerUserName");
			return (Criteria) this;
		}

		public Criteria andSellerUserNameIn(List<String> values) {
			addCriterion("seller_user_name in", values, "sellerUserName");
			return (Criteria) this;
		}

		public Criteria andSellerUserNameNotIn(List<String> values) {
			addCriterion("seller_user_name not in", values, "sellerUserName");
			return (Criteria) this;
		}

		public Criteria andSellerUserNameBetween(String value1, String value2) {
			addCriterion("seller_user_name between", value1, value2,
					"sellerUserName");
			return (Criteria) this;
		}

		public Criteria andSellerUserNameNotBetween(String value1, String value2) {
			addCriterion("seller_user_name not between", value1, value2,
					"sellerUserName");
			return (Criteria) this;
		}

		public Criteria andProductNameIsNull() {
			addCriterion("product_name is null");
			return (Criteria) this;
		}

		public Criteria andProductNameIsNotNull() {
			addCriterion("product_name is not null");
			return (Criteria) this;
		}

		public Criteria andProductNameEqualTo(String value) {
			addCriterion("product_name =", value, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameNotEqualTo(String value) {
			addCriterion("product_name <>", value, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameGreaterThan(String value) {
			addCriterion("product_name >", value, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameGreaterThanOrEqualTo(String value) {
			addCriterion("product_name >=", value, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameLessThan(String value) {
			addCriterion("product_name <", value, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameLessThanOrEqualTo(String value) {
			addCriterion("product_name <=", value, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameLike(String value) {
			addCriterion("product_name like", value, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameNotLike(String value) {
			addCriterion("product_name not like", value, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameIn(List<String> values) {
			addCriterion("product_name in", values, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameNotIn(List<String> values) {
			addCriterion("product_name not in", values, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameBetween(String value1, String value2) {
			addCriterion("product_name between", value1, value2, "productName");
			return (Criteria) this;
		}

		public Criteria andProductNameNotBetween(String value1, String value2) {
			addCriterion("product_name not between", value1, value2,
					"productName");
			return (Criteria) this;
		}

		public Criteria andProductTitleIsNull() {
			addCriterion("product_title is null");
			return (Criteria) this;
		}

		public Criteria andProductTitleIsNotNull() {
			addCriterion("product_title is not null");
			return (Criteria) this;
		}

		public Criteria andProductTitleEqualTo(String value) {
			addCriterion("product_title =", value, "productTitle");
			return (Criteria) this;
		}

		public Criteria andProductTitleNotEqualTo(String value) {
			addCriterion("product_title <>", value, "productTitle");
			return (Criteria) this;
		}

		public Criteria andProductTitleGreaterThan(String value) {
			addCriterion("product_title >", value, "productTitle");
			return (Criteria) this;
		}

		public Criteria andProductTitleGreaterThanOrEqualTo(String value) {
			addCriterion("product_title >=", value, "productTitle");
			return (Criteria) this;
		}

		public Criteria andProductTitleLessThan(String value) {
			addCriterion("product_title <", value, "productTitle");
			return (Criteria) this;
		}

		public Criteria andProductTitleLessThanOrEqualTo(String value) {
			addCriterion("product_title <=", value, "productTitle");
			return (Criteria) this;
		}

		public Criteria andProductTitleLike(String value) {
			addCriterion("product_title like", value, "productTitle");
			return (Criteria) this;
		}

		public Criteria andProductTitleNotLike(String value) {
			addCriterion("product_title not like", value, "productTitle");
			return (Criteria) this;
		}

		public Criteria andProductTitleIn(List<String> values) {
			addCriterion("product_title in", values, "productTitle");
			return (Criteria) this;
		}

		public Criteria andProductTitleNotIn(List<String> values) {
			addCriterion("product_title not in", values, "productTitle");
			return (Criteria) this;
		}

		public Criteria andProductTitleBetween(String value1, String value2) {
			addCriterion("product_title between", value1, value2,
					"productTitle");
			return (Criteria) this;
		}

		public Criteria andProductTitleNotBetween(String value1, String value2) {
			addCriterion("product_title not between", value1, value2,
					"productTitle");
			return (Criteria) this;
		}

		public Criteria andBrandIdIsNull() {
			addCriterion("brand_id is null");
			return (Criteria) this;
		}

		public Criteria andBrandIdIsNotNull() {
			addCriterion("brand_id is not null");
			return (Criteria) this;
		}

		public Criteria andBrandIdEqualTo(Long value) {
			addCriterion("brand_id =", value, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdNotEqualTo(Long value) {
			addCriterion("brand_id <>", value, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdGreaterThan(Long value) {
			addCriterion("brand_id >", value, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdGreaterThanOrEqualTo(Long value) {
			addCriterion("brand_id >=", value, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdLessThan(Long value) {
			addCriterion("brand_id <", value, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdLessThanOrEqualTo(Long value) {
			addCriterion("brand_id <=", value, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdIn(List<Long> values) {
			addCriterion("brand_id in", values, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdNotIn(List<Long> values) {
			addCriterion("brand_id not in", values, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdBetween(Long value1, Long value2) {
			addCriterion("brand_id between", value1, value2, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdNotBetween(Long value1, Long value2) {
			addCriterion("brand_id not between", value1, value2, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandNameIsNull() {
			addCriterion("brand_name is null");
			return (Criteria) this;
		}

		public Criteria andBrandNameIsNotNull() {
			addCriterion("brand_name is not null");
			return (Criteria) this;
		}

		public Criteria andBrandNameEqualTo(String value) {
			addCriterion("brand_name =", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameNotEqualTo(String value) {
			addCriterion("brand_name <>", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameGreaterThan(String value) {
			addCriterion("brand_name >", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameGreaterThanOrEqualTo(String value) {
			addCriterion("brand_name >=", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameLessThan(String value) {
			addCriterion("brand_name <", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameLessThanOrEqualTo(String value) {
			addCriterion("brand_name <=", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameLike(String value) {
			addCriterion("brand_name like", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameNotLike(String value) {
			addCriterion("brand_name not like", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameIn(List<String> values) {
			addCriterion("brand_name in", values, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameNotIn(List<String> values) {
			addCriterion("brand_name not in", values, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameBetween(String value1, String value2) {
			addCriterion("brand_name between", value1, value2, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameNotBetween(String value1, String value2) {
			addCriterion("brand_name not between", value1, value2, "brandName");
			return (Criteria) this;
		}

		public Criteria andViewNumIsNull() {
			addCriterion("view_num is null");
			return (Criteria) this;
		}

		public Criteria andViewNumIsNotNull() {
			addCriterion("view_num is not null");
			return (Criteria) this;
		}

		public Criteria andViewNumEqualTo(Long value) {
			addCriterion("view_num =", value, "viewNum");
			return (Criteria) this;
		}

		public Criteria andViewNumNotEqualTo(Long value) {
			addCriterion("view_num <>", value, "viewNum");
			return (Criteria) this;
		}

		public Criteria andViewNumGreaterThan(Long value) {
			addCriterion("view_num >", value, "viewNum");
			return (Criteria) this;
		}

		public Criteria andViewNumGreaterThanOrEqualTo(Long value) {
			addCriterion("view_num >=", value, "viewNum");
			return (Criteria) this;
		}

		public Criteria andViewNumLessThan(Long value) {
			addCriterion("view_num <", value, "viewNum");
			return (Criteria) this;
		}

		public Criteria andViewNumLessThanOrEqualTo(Long value) {
			addCriterion("view_num <=", value, "viewNum");
			return (Criteria) this;
		}

		public Criteria andViewNumIn(List<Long> values) {
			addCriterion("view_num in", values, "viewNum");
			return (Criteria) this;
		}

		public Criteria andViewNumNotIn(List<Long> values) {
			addCriterion("view_num not in", values, "viewNum");
			return (Criteria) this;
		}

		public Criteria andViewNumBetween(Long value1, Long value2) {
			addCriterion("view_num between", value1, value2, "viewNum");
			return (Criteria) this;
		}

		public Criteria andViewNumNotBetween(Long value1, Long value2) {
			addCriterion("view_num not between", value1, value2, "viewNum");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Short value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Short value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Short value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Short value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Short value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Short value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Short> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Short> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Short value1, Short value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Short value1, Short value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andPayTypeIsNull() {
			addCriterion("pay_type is null");
			return (Criteria) this;
		}

		public Criteria andPayTypeIsNotNull() {
			addCriterion("pay_type is not null");
			return (Criteria) this;
		}

		public Criteria andPayTypeEqualTo(Short value) {
			addCriterion("pay_type =", value, "payType");
			return (Criteria) this;
		}

		public Criteria andPayTypeNotEqualTo(Short value) {
			addCriterion("pay_type <>", value, "payType");
			return (Criteria) this;
		}

		public Criteria andPayTypeGreaterThan(Short value) {
			addCriterion("pay_type >", value, "payType");
			return (Criteria) this;
		}

		public Criteria andPayTypeGreaterThanOrEqualTo(Short value) {
			addCriterion("pay_type >=", value, "payType");
			return (Criteria) this;
		}

		public Criteria andPayTypeLessThan(Short value) {
			addCriterion("pay_type <", value, "payType");
			return (Criteria) this;
		}

		public Criteria andPayTypeLessThanOrEqualTo(Short value) {
			addCriterion("pay_type <=", value, "payType");
			return (Criteria) this;
		}

		public Criteria andPayTypeIn(List<Short> values) {
			addCriterion("pay_type in", values, "payType");
			return (Criteria) this;
		}

		public Criteria andPayTypeNotIn(List<Short> values) {
			addCriterion("pay_type not in", values, "payType");
			return (Criteria) this;
		}

		public Criteria andPayTypeBetween(Short value1, Short value2) {
			addCriterion("pay_type between", value1, value2, "payType");
			return (Criteria) this;
		}

		public Criteria andPayTypeNotBetween(Short value1, Short value2) {
			addCriterion("pay_type not between", value1, value2, "payType");
			return (Criteria) this;
		}

		public Criteria andExpressFeeIsNull() {
			addCriterion("express_fee is null");
			return (Criteria) this;
		}

		public Criteria andExpressFeeIsNotNull() {
			addCriterion("express_fee is not null");
			return (Criteria) this;
		}

		public Criteria andExpressFeeEqualTo(Integer value) {
			addCriterion("express_fee =", value, "expressFee");
			return (Criteria) this;
		}

		public Criteria andExpressFeeNotEqualTo(Integer value) {
			addCriterion("express_fee <>", value, "expressFee");
			return (Criteria) this;
		}

		public Criteria andExpressFeeGreaterThan(Integer value) {
			addCriterion("express_fee >", value, "expressFee");
			return (Criteria) this;
		}

		public Criteria andExpressFeeGreaterThanOrEqualTo(Integer value) {
			addCriterion("express_fee >=", value, "expressFee");
			return (Criteria) this;
		}

		public Criteria andExpressFeeLessThan(Integer value) {
			addCriterion("express_fee <", value, "expressFee");
			return (Criteria) this;
		}

		public Criteria andExpressFeeLessThanOrEqualTo(Integer value) {
			addCriterion("express_fee <=", value, "expressFee");
			return (Criteria) this;
		}

		public Criteria andExpressFeeIn(List<Integer> values) {
			addCriterion("express_fee in", values, "expressFee");
			return (Criteria) this;
		}

		public Criteria andExpressFeeNotIn(List<Integer> values) {
			addCriterion("express_fee not in", values, "expressFee");
			return (Criteria) this;
		}

		public Criteria andExpressFeeBetween(Integer value1, Integer value2) {
			addCriterion("express_fee between", value1, value2, "expressFee");
			return (Criteria) this;
		}

		public Criteria andExpressFeeNotBetween(Integer value1, Integer value2) {
			addCriterion("express_fee not between", value1, value2,
					"expressFee");
			return (Criteria) this;
		}

		public Criteria andPicUrlIsNull() {
			addCriterion("pic_url is null");
			return (Criteria) this;
		}

		public Criteria andPicUrlIsNotNull() {
			addCriterion("pic_url is not null");
			return (Criteria) this;
		}

		public Criteria andPicUrlEqualTo(String value) {
			addCriterion("pic_url =", value, "picUrl");
			return (Criteria) this;
		}

		public Criteria andPicUrlNotEqualTo(String value) {
			addCriterion("pic_url <>", value, "picUrl");
			return (Criteria) this;
		}

		public Criteria andPicUrlGreaterThan(String value) {
			addCriterion("pic_url >", value, "picUrl");
			return (Criteria) this;
		}

		public Criteria andPicUrlGreaterThanOrEqualTo(String value) {
			addCriterion("pic_url >=", value, "picUrl");
			return (Criteria) this;
		}

		public Criteria andPicUrlLessThan(String value) {
			addCriterion("pic_url <", value, "picUrl");
			return (Criteria) this;
		}

		public Criteria andPicUrlLessThanOrEqualTo(String value) {
			addCriterion("pic_url <=", value, "picUrl");
			return (Criteria) this;
		}

		public Criteria andPicUrlLike(String value) {
			addCriterion("pic_url like", value, "picUrl");
			return (Criteria) this;
		}

		public Criteria andPicUrlNotLike(String value) {
			addCriterion("pic_url not like", value, "picUrl");
			return (Criteria) this;
		}

		public Criteria andPicUrlIn(List<String> values) {
			addCriterion("pic_url in", values, "picUrl");
			return (Criteria) this;
		}

		public Criteria andPicUrlNotIn(List<String> values) {
			addCriterion("pic_url not in", values, "picUrl");
			return (Criteria) this;
		}

		public Criteria andPicUrlBetween(String value1, String value2) {
			addCriterion("pic_url between", value1, value2, "picUrl");
			return (Criteria) this;
		}

		public Criteria andPicUrlNotBetween(String value1, String value2) {
			addCriterion("pic_url not between", value1, value2, "picUrl");
			return (Criteria) this;
		}

		public Criteria andCommentTimesIsNull() {
			addCriterion("comment_times is null");
			return (Criteria) this;
		}

		public Criteria andCommentTimesIsNotNull() {
			addCriterion("comment_times is not null");
			return (Criteria) this;
		}

		public Criteria andCommentTimesEqualTo(Integer value) {
			addCriterion("comment_times =", value, "commentTimes");
			return (Criteria) this;
		}

		public Criteria andCommentTimesNotEqualTo(Integer value) {
			addCriterion("comment_times <>", value, "commentTimes");
			return (Criteria) this;
		}

		public Criteria andCommentTimesGreaterThan(Integer value) {
			addCriterion("comment_times >", value, "commentTimes");
			return (Criteria) this;
		}

		public Criteria andCommentTimesGreaterThanOrEqualTo(Integer value) {
			addCriterion("comment_times >=", value, "commentTimes");
			return (Criteria) this;
		}

		public Criteria andCommentTimesLessThan(Integer value) {
			addCriterion("comment_times <", value, "commentTimes");
			return (Criteria) this;
		}

		public Criteria andCommentTimesLessThanOrEqualTo(Integer value) {
			addCriterion("comment_times <=", value, "commentTimes");
			return (Criteria) this;
		}

		public Criteria andCommentTimesIn(List<Integer> values) {
			addCriterion("comment_times in", values, "commentTimes");
			return (Criteria) this;
		}

		public Criteria andCommentTimesNotIn(List<Integer> values) {
			addCriterion("comment_times not in", values, "commentTimes");
			return (Criteria) this;
		}

		public Criteria andCommentTimesBetween(Integer value1, Integer value2) {
			addCriterion("comment_times between", value1, value2,
					"commentTimes");
			return (Criteria) this;
		}

		public Criteria andCommentTimesNotBetween(Integer value1, Integer value2) {
			addCriterion("comment_times not between", value1, value2,
					"commentTimes");
			return (Criteria) this;
		}

		public Criteria andScoreIsNull() {
			addCriterion("score is null");
			return (Criteria) this;
		}

		public Criteria andScoreIsNotNull() {
			addCriterion("score is not null");
			return (Criteria) this;
		}

		public Criteria andScoreEqualTo(Integer value) {
			addCriterion("score =", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotEqualTo(Integer value) {
			addCriterion("score <>", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreGreaterThan(Integer value) {
			addCriterion("score >", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreGreaterThanOrEqualTo(Integer value) {
			addCriterion("score >=", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreLessThan(Integer value) {
			addCriterion("score <", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreLessThanOrEqualTo(Integer value) {
			addCriterion("score <=", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreIn(List<Integer> values) {
			addCriterion("score in", values, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotIn(List<Integer> values) {
			addCriterion("score not in", values, "score");
			return (Criteria) this;
		}

		public Criteria andScoreBetween(Integer value1, Integer value2) {
			addCriterion("score between", value1, value2, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotBetween(Integer value1, Integer value2) {
			addCriterion("score not between", value1, value2, "score");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2,
					"createTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("update_time is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("update_time is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("update_time =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("update_time <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("update_time >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("update_time >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("update_time <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("update_time <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterion("update_time in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterion("update_time not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("update_time between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("update_time not between", value1, value2,
					"updateTime");
			return (Criteria) this;
		}

		public Criteria andSalesIsNull() {
			addCriterion("sales is null");
			return (Criteria) this;
		}

		public Criteria andSalesIsNotNull() {
			addCriterion("sales is not null");
			return (Criteria) this;
		}

		public Criteria andSalesEqualTo(Integer value) {
			addCriterion("sales =", value, "sales");
			return (Criteria) this;
		}

		public Criteria andSalesNotEqualTo(Integer value) {
			addCriterion("sales <>", value, "sales");
			return (Criteria) this;
		}

		public Criteria andSalesGreaterThan(Integer value) {
			addCriterion("sales >", value, "sales");
			return (Criteria) this;
		}

		public Criteria andSalesGreaterThanOrEqualTo(Integer value) {
			addCriterion("sales >=", value, "sales");
			return (Criteria) this;
		}

		public Criteria andSalesLessThan(Integer value) {
			addCriterion("sales <", value, "sales");
			return (Criteria) this;
		}

		public Criteria andSalesLessThanOrEqualTo(Integer value) {
			addCriterion("sales <=", value, "sales");
			return (Criteria) this;
		}

		public Criteria andSalesIn(List<Integer> values) {
			addCriterion("sales in", values, "sales");
			return (Criteria) this;
		}

		public Criteria andSalesNotIn(List<Integer> values) {
			addCriterion("sales not in", values, "sales");
			return (Criteria) this;
		}

		public Criteria andSalesBetween(Integer value1, Integer value2) {
			addCriterion("sales between", value1, value2, "sales");
			return (Criteria) this;
		}

		public Criteria andSalesNotBetween(Integer value1, Integer value2) {
			addCriterion("sales not between", value1, value2, "sales");
			return (Criteria) this;
		}

		public Criteria andDefaultGoodsIdIsNull() {
			addCriterion("default_goods_id is null");
			return (Criteria) this;
		}

		public Criteria andDefaultGoodsIdIsNotNull() {
			addCriterion("default_goods_id is not null");
			return (Criteria) this;
		}

		public Criteria andDefaultGoodsIdEqualTo(Long value) {
			addCriterion("default_goods_id =", value, "defaultGoodsId");
			return (Criteria) this;
		}

		public Criteria andDefaultGoodsIdNotEqualTo(Long value) {
			addCriterion("default_goods_id <>", value, "defaultGoodsId");
			return (Criteria) this;
		}

		public Criteria andDefaultGoodsIdGreaterThan(Long value) {
			addCriterion("default_goods_id >", value, "defaultGoodsId");
			return (Criteria) this;
		}

		public Criteria andDefaultGoodsIdGreaterThanOrEqualTo(Long value) {
			addCriterion("default_goods_id >=", value, "defaultGoodsId");
			return (Criteria) this;
		}

		public Criteria andDefaultGoodsIdLessThan(Long value) {
			addCriterion("default_goods_id <", value, "defaultGoodsId");
			return (Criteria) this;
		}

		public Criteria andDefaultGoodsIdLessThanOrEqualTo(Long value) {
			addCriterion("default_goods_id <=", value, "defaultGoodsId");
			return (Criteria) this;
		}

		public Criteria andDefaultGoodsIdIn(List<Long> values) {
			addCriterion("default_goods_id in", values, "defaultGoodsId");
			return (Criteria) this;
		}

		public Criteria andDefaultGoodsIdNotIn(List<Long> values) {
			addCriterion("default_goods_id not in", values, "defaultGoodsId");
			return (Criteria) this;
		}

		public Criteria andDefaultGoodsIdBetween(Long value1, Long value2) {
			addCriterion("default_goods_id between", value1, value2,
					"defaultGoodsId");
			return (Criteria) this;
		}

		public Criteria andDefaultGoodsIdNotBetween(Long value1, Long value2) {
			addCriterion("default_goods_id not between", value1, value2,
					"defaultGoodsId");
			return (Criteria) this;
		}

		public Criteria andDefaultPriceIsNull() {
			addCriterion("default_price is null");
			return (Criteria) this;
		}

		public Criteria andDefaultPriceIsNotNull() {
			addCriterion("default_price is not null");
			return (Criteria) this;
		}

		public Criteria andDefaultPriceEqualTo(Integer value) {
			addCriterion("default_price =", value, "defaultPrice");
			return (Criteria) this;
		}

		public Criteria andDefaultPriceNotEqualTo(Integer value) {
			addCriterion("default_price <>", value, "defaultPrice");
			return (Criteria) this;
		}

		public Criteria andDefaultPriceGreaterThan(Integer value) {
			addCriterion("default_price >", value, "defaultPrice");
			return (Criteria) this;
		}

		public Criteria andDefaultPriceGreaterThanOrEqualTo(Integer value) {
			addCriterion("default_price >=", value, "defaultPrice");
			return (Criteria) this;
		}

		public Criteria andDefaultPriceLessThan(Integer value) {
			addCriterion("default_price <", value, "defaultPrice");
			return (Criteria) this;
		}

		public Criteria andDefaultPriceLessThanOrEqualTo(Integer value) {
			addCriterion("default_price <=", value, "defaultPrice");
			return (Criteria) this;
		}

		public Criteria andDefaultPriceIn(List<Integer> values) {
			addCriterion("default_price in", values, "defaultPrice");
			return (Criteria) this;
		}

		public Criteria andDefaultPriceNotIn(List<Integer> values) {
			addCriterion("default_price not in", values, "defaultPrice");
			return (Criteria) this;
		}

		public Criteria andDefaultPriceBetween(Integer value1, Integer value2) {
			addCriterion("default_price between", value1, value2,
					"defaultPrice");
			return (Criteria) this;
		}

		public Criteria andDefaultPriceNotBetween(Integer value1, Integer value2) {
			addCriterion("default_price not between", value1, value2,
					"defaultPrice");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table product
	 * @mbggenerated  Mon Nov 24 16:04:02 CST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbggenerated do_not_delete_during_merge Thu Jun 12 11:22:43 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}