package com.mission.shop.product.dao.model;

import java.io.Serializable;
import java.util.Date;

public class Shop implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shop.shop_id
	 * @mbggenerated  Mon Nov 24 16:04:02 CST 2014
	 */
	private Long shopId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shop.shop_name
	 * @mbggenerated  Mon Nov 24 16:04:02 CST 2014
	 */
	private String shopName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shop.link_men
	 * @mbggenerated  Mon Nov 24 16:04:02 CST 2014
	 */
	private String linkMen;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shop.phone_num
	 * @mbggenerated  Mon Nov 24 16:04:02 CST 2014
	 */
	private String phoneNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shop.create_time
	 * @mbggenerated  Mon Nov 24 16:04:02 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shop.update_time
	 * @mbggenerated  Mon Nov 24 16:04:02 CST 2014
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shop.status
	 * @mbggenerated  Mon Nov 24 16:04:02 CST 2014
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shop.seller_id
	 * @mbggenerated  Mon Nov 24 16:04:02 CST 2014
	 */
	private Long sellerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shop.seller_user_name
	 * @mbggenerated  Mon Nov 24 16:04:02 CST 2014
	 */
	private String sellerUserName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table shop
	 * @mbggenerated  Mon Nov 24 16:04:02 CST 2014
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shop.shop_id
	 * @return  the value of shop.shop_id
	 * @mbggenerated  Mon Nov 24 16:04:02 CST 2014
	 */
	public Long getShopId() {
		return shopId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shop.shop_id
	 * @param shopId  the value for shop.shop_id
	 * @mbggenerated  Mon Nov 24 16:04:02 CST 2014
	 */
	public void setShopId(Long shopId) {
		this.shopId = shopId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shop.shop_name
	 * @return  the value of shop.shop_name
	 * @mbggenerated  Mon Nov 24 16:04:02 CST 2014
	 */
	public String getShopName() {
		return shopName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shop.shop_name
	 * @param shopName  the value for shop.shop_name
	 * @mbggenerated  Mon Nov 24 16:04:02 CST 2014
	 */
	public void setShopName(String shopName) {
		this.shopName = shopName == null ? null : shopName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shop.link_men
	 * @return  the value of shop.link_men
	 * @mbggenerated  Mon Nov 24 16:04:02 CST 2014
	 */
	public String getLinkMen() {
		return linkMen;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shop.link_men
	 * @param linkMen  the value for shop.link_men
	 * @mbggenerated  Mon Nov 24 16:04:02 CST 2014
	 */
	public void setLinkMen(String linkMen) {
		this.linkMen = linkMen == null ? null : linkMen.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shop.phone_num
	 * @return  the value of shop.phone_num
	 * @mbggenerated  Mon Nov 24 16:04:02 CST 2014
	 */
	public String getPhoneNum() {
		return phoneNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shop.phone_num
	 * @param phoneNum  the value for shop.phone_num
	 * @mbggenerated  Mon Nov 24 16:04:02 CST 2014
	 */
	public void setPhoneNum(String phoneNum) {
		this.phoneNum = phoneNum == null ? null : phoneNum.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shop.create_time
	 * @return  the value of shop.create_time
	 * @mbggenerated  Mon Nov 24 16:04:02 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shop.create_time
	 * @param createTime  the value for shop.create_time
	 * @mbggenerated  Mon Nov 24 16:04:02 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shop.update_time
	 * @return  the value of shop.update_time
	 * @mbggenerated  Mon Nov 24 16:04:02 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shop.update_time
	 * @param updateTime  the value for shop.update_time
	 * @mbggenerated  Mon Nov 24 16:04:02 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shop.status
	 * @return  the value of shop.status
	 * @mbggenerated  Mon Nov 24 16:04:02 CST 2014
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shop.status
	 * @param status  the value for shop.status
	 * @mbggenerated  Mon Nov 24 16:04:02 CST 2014
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shop.seller_id
	 * @return  the value of shop.seller_id
	 * @mbggenerated  Mon Nov 24 16:04:02 CST 2014
	 */
	public Long getSellerId() {
		return sellerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shop.seller_id
	 * @param sellerId  the value for shop.seller_id
	 * @mbggenerated  Mon Nov 24 16:04:02 CST 2014
	 */
	public void setSellerId(Long sellerId) {
		this.sellerId = sellerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shop.seller_user_name
	 * @return  the value of shop.seller_user_name
	 * @mbggenerated  Mon Nov 24 16:04:02 CST 2014
	 */
	public String getSellerUserName() {
		return sellerUserName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shop.seller_user_name
	 * @param sellerUserName  the value for shop.seller_user_name
	 * @mbggenerated  Mon Nov 24 16:04:02 CST 2014
	 */
	public void setSellerUserName(String sellerUserName) {
		this.sellerUserName = sellerUserName == null ? null : sellerUserName
				.trim();
	}
}