package com.mission.shop.user.dao.model;

import java.io.Serializable;
import java.util.Date;

public class UserRank implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_rank.rank_id
	 * @mbggenerated  Thu Jul 17 14:46:19 CST 2014
	 */
	private Integer rankId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_rank.rank
	 * @mbggenerated  Thu Jul 17 14:46:19 CST 2014
	 */
	private Integer rank;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_rank.rank_name
	 * @mbggenerated  Thu Jul 17 14:46:19 CST 2014
	 */
	private String rankName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_rank.create_time
	 * @mbggenerated  Thu Jul 17 14:46:19 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_rank.update_time
	 * @mbggenerated  Thu Jul 17 14:46:19 CST 2014
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_rank.status
	 * @mbggenerated  Thu Jul 17 14:46:19 CST 2014
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user_rank
	 * @mbggenerated  Thu Jul 17 14:46:19 CST 2014
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_rank.rank_id
	 * @return  the value of user_rank.rank_id
	 * @mbggenerated  Thu Jul 17 14:46:19 CST 2014
	 */
	public Integer getRankId() {
		return rankId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_rank.rank_id
	 * @param rankId  the value for user_rank.rank_id
	 * @mbggenerated  Thu Jul 17 14:46:19 CST 2014
	 */
	public void setRankId(Integer rankId) {
		this.rankId = rankId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_rank.rank
	 * @return  the value of user_rank.rank
	 * @mbggenerated  Thu Jul 17 14:46:19 CST 2014
	 */
	public Integer getRank() {
		return rank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_rank.rank
	 * @param rank  the value for user_rank.rank
	 * @mbggenerated  Thu Jul 17 14:46:19 CST 2014
	 */
	public void setRank(Integer rank) {
		this.rank = rank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_rank.rank_name
	 * @return  the value of user_rank.rank_name
	 * @mbggenerated  Thu Jul 17 14:46:19 CST 2014
	 */
	public String getRankName() {
		return rankName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_rank.rank_name
	 * @param rankName  the value for user_rank.rank_name
	 * @mbggenerated  Thu Jul 17 14:46:19 CST 2014
	 */
	public void setRankName(String rankName) {
		this.rankName = rankName == null ? null : rankName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_rank.create_time
	 * @return  the value of user_rank.create_time
	 * @mbggenerated  Thu Jul 17 14:46:19 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_rank.create_time
	 * @param createTime  the value for user_rank.create_time
	 * @mbggenerated  Thu Jul 17 14:46:19 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_rank.update_time
	 * @return  the value of user_rank.update_time
	 * @mbggenerated  Thu Jul 17 14:46:19 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_rank.update_time
	 * @param updateTime  the value for user_rank.update_time
	 * @mbggenerated  Thu Jul 17 14:46:19 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_rank.status
	 * @return  the value of user_rank.status
	 * @mbggenerated  Thu Jul 17 14:46:19 CST 2014
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_rank.status
	 * @param status  the value for user_rank.status
	 * @mbggenerated  Thu Jul 17 14:46:19 CST 2014
	 */
	public void setStatus(Short status) {
		this.status = status;
	}
}