package com.mission.shop.product.dao.mapper;

import com.mission.shop.product.dao.model.PackingList;
import com.mission.shop.product.dao.model.PackingListExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PackingListMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packing_list
	 * @mbggenerated  Mon Jul 28 21:25:09 CST 2014
	 */
	int countByExample(PackingListExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packing_list
	 * @mbggenerated  Mon Jul 28 21:25:09 CST 2014
	 */
	int deleteByExample(PackingListExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packing_list
	 * @mbggenerated  Mon Jul 28 21:25:09 CST 2014
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packing_list
	 * @mbggenerated  Mon Jul 28 21:25:09 CST 2014
	 */
	int insert(PackingList record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packing_list
	 * @mbggenerated  Mon Jul 28 21:25:09 CST 2014
	 */
	int insertSelective(PackingList record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packing_list
	 * @mbggenerated  Mon Jul 28 21:25:09 CST 2014
	 */
	List<PackingList> selectByExample(PackingListExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packing_list
	 * @mbggenerated  Mon Jul 28 21:25:09 CST 2014
	 */
	PackingList selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packing_list
	 * @mbggenerated  Mon Jul 28 21:25:09 CST 2014
	 */
	int updateByExampleSelective(@Param("record") PackingList record,
			@Param("example") PackingListExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packing_list
	 * @mbggenerated  Mon Jul 28 21:25:09 CST 2014
	 */
	int updateByExample(@Param("record") PackingList record,
			@Param("example") PackingListExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packing_list
	 * @mbggenerated  Mon Jul 28 21:25:09 CST 2014
	 */
	int updateByPrimaryKeySelective(PackingList record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table packing_list
	 * @mbggenerated  Mon Jul 28 21:25:09 CST 2014
	 */
	int updateByPrimaryKey(PackingList record);
}