package com.mission.shop.product.dao.mapper;

import com.mission.shop.product.dao.model.ProductPic;
import com.mission.shop.product.dao.model.ProductPicExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductPicMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_pic
	 * @mbggenerated  Mon Jul 28 21:25:09 CST 2014
	 */
	int countByExample(ProductPicExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_pic
	 * @mbggenerated  Mon Jul 28 21:25:09 CST 2014
	 */
	int deleteByExample(ProductPicExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_pic
	 * @mbggenerated  Mon Jul 28 21:25:09 CST 2014
	 */
	int deleteByPrimaryKey(Long productPicId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_pic
	 * @mbggenerated  Mon Jul 28 21:25:09 CST 2014
	 */
	int insert(ProductPic record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_pic
	 * @mbggenerated  Mon Jul 28 21:25:09 CST 2014
	 */
	int insertSelective(ProductPic record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_pic
	 * @mbggenerated  Mon Jul 28 21:25:09 CST 2014
	 */
	List<ProductPic> selectByExample(ProductPicExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_pic
	 * @mbggenerated  Mon Jul 28 21:25:09 CST 2014
	 */
	ProductPic selectByPrimaryKey(Long productPicId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_pic
	 * @mbggenerated  Mon Jul 28 21:25:09 CST 2014
	 */
	int updateByExampleSelective(@Param("record") ProductPic record,
			@Param("example") ProductPicExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_pic
	 * @mbggenerated  Mon Jul 28 21:25:09 CST 2014
	 */
	int updateByExample(@Param("record") ProductPic record,
			@Param("example") ProductPicExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_pic
	 * @mbggenerated  Mon Jul 28 21:25:09 CST 2014
	 */
	int updateByPrimaryKeySelective(ProductPic record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_pic
	 * @mbggenerated  Mon Jul 28 21:25:09 CST 2014
	 */
	int updateByPrimaryKey(ProductPic record);
}