package com.mission.shop.user.dao.mapper;

import com.mission.shop.user.dao.model.UserIntegeral;
import com.mission.shop.user.dao.model.UserIntegeralExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserIntegeralMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_integeral
     *
     * @mbggenerated Sat Aug 02 20:57:04 CST 2014
     */
    int countByExample(UserIntegeralExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_integeral
     *
     * @mbggenerated Sat Aug 02 20:57:04 CST 2014
     */
    int deleteByExample(UserIntegeralExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_integeral
     *
     * @mbggenerated Sat Aug 02 20:57:04 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_integeral
     *
     * @mbggenerated Sat Aug 02 20:57:04 CST 2014
     */
    int insert(UserIntegeral record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_integeral
     *
     * @mbggenerated Sat Aug 02 20:57:04 CST 2014
     */
    int insertSelective(UserIntegeral record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_integeral
     *
     * @mbggenerated Sat Aug 02 20:57:04 CST 2014
     */
    List<UserIntegeral> selectByExample(UserIntegeralExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_integeral
     *
     * @mbggenerated Sat Aug 02 20:57:04 CST 2014
     */
    UserIntegeral selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_integeral
     *
     * @mbggenerated Sat Aug 02 20:57:04 CST 2014
     */
    int updateByExampleSelective(@Param("record") UserIntegeral record, @Param("example") UserIntegeralExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_integeral
     *
     * @mbggenerated Sat Aug 02 20:57:04 CST 2014
     */
    int updateByExample(@Param("record") UserIntegeral record, @Param("example") UserIntegeralExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_integeral
     *
     * @mbggenerated Sat Aug 02 20:57:04 CST 2014
     */
    int updateByPrimaryKeySelective(UserIntegeral record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_integeral
     *
     * @mbggenerated Sat Aug 02 20:57:04 CST 2014
     */
    int updateByPrimaryKey(UserIntegeral record);
}