package com.mission.shop.order.dao.model;

import java.io.Serializable;
import java.util.Date;

public class Invoice implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column invoice.invoice_id
	 * @mbggenerated  Mon Jul 28 13:52:51 CST 2014
	 */
	private Long invoiceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column invoice.type
	 * @mbggenerated  Mon Jul 28 13:52:51 CST 2014
	 */
	private Short type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column invoice.title
	 * @mbggenerated  Mon Jul 28 13:52:51 CST 2014
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column invoice.product_type
	 * @mbggenerated  Mon Jul 28 13:52:51 CST 2014
	 */
	private Short productType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column invoice.create_time
	 * @mbggenerated  Mon Jul 28 13:52:51 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table invoice
	 * @mbggenerated  Mon Jul 28 13:52:51 CST 2014
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column invoice.invoice_id
	 * @return  the value of invoice.invoice_id
	 * @mbggenerated  Mon Jul 28 13:52:51 CST 2014
	 */
	public Long getInvoiceId() {
		return invoiceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column invoice.invoice_id
	 * @param invoiceId  the value for invoice.invoice_id
	 * @mbggenerated  Mon Jul 28 13:52:51 CST 2014
	 */
	public void setInvoiceId(Long invoiceId) {
		this.invoiceId = invoiceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column invoice.type
	 * @return  the value of invoice.type
	 * @mbggenerated  Mon Jul 28 13:52:51 CST 2014
	 */
	public Short getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column invoice.type
	 * @param type  the value for invoice.type
	 * @mbggenerated  Mon Jul 28 13:52:51 CST 2014
	 */
	public void setType(Short type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column invoice.title
	 * @return  the value of invoice.title
	 * @mbggenerated  Mon Jul 28 13:52:51 CST 2014
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column invoice.title
	 * @param title  the value for invoice.title
	 * @mbggenerated  Mon Jul 28 13:52:51 CST 2014
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column invoice.product_type
	 * @return  the value of invoice.product_type
	 * @mbggenerated  Mon Jul 28 13:52:51 CST 2014
	 */
	public Short getProductType() {
		return productType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column invoice.product_type
	 * @param productType  the value for invoice.product_type
	 * @mbggenerated  Mon Jul 28 13:52:51 CST 2014
	 */
	public void setProductType(Short productType) {
		this.productType = productType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column invoice.create_time
	 * @return  the value of invoice.create_time
	 * @mbggenerated  Mon Jul 28 13:52:51 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column invoice.create_time
	 * @param createTime  the value for invoice.create_time
	 * @mbggenerated  Mon Jul 28 13:52:51 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}