package com.mission.shop.order.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class InvoiceExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table invoice
	 * @mbggenerated  Fri Jul 18 11:24:51 CST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table invoice
	 * @mbggenerated  Fri Jul 18 11:24:51 CST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table invoice
	 * @mbggenerated  Fri Jul 18 11:24:51 CST 2014
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invoice
	 * @mbggenerated  Fri Jul 18 11:24:51 CST 2014
	 */
	public InvoiceExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invoice
	 * @mbggenerated  Fri Jul 18 11:24:51 CST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invoice
	 * @mbggenerated  Fri Jul 18 11:24:51 CST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invoice
	 * @mbggenerated  Fri Jul 18 11:24:51 CST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invoice
	 * @mbggenerated  Fri Jul 18 11:24:51 CST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invoice
	 * @mbggenerated  Fri Jul 18 11:24:51 CST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invoice
	 * @mbggenerated  Fri Jul 18 11:24:51 CST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invoice
	 * @mbggenerated  Fri Jul 18 11:24:51 CST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invoice
	 * @mbggenerated  Fri Jul 18 11:24:51 CST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invoice
	 * @mbggenerated  Fri Jul 18 11:24:51 CST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invoice
	 * @mbggenerated  Fri Jul 18 11:24:51 CST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table invoice
	 * @mbggenerated  Fri Jul 18 11:24:51 CST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andInvoiceIdIsNull() {
			addCriterion("invoice_id is null");
			return (Criteria) this;
		}

		public Criteria andInvoiceIdIsNotNull() {
			addCriterion("invoice_id is not null");
			return (Criteria) this;
		}

		public Criteria andInvoiceIdEqualTo(Long value) {
			addCriterion("invoice_id =", value, "invoiceId");
			return (Criteria) this;
		}

		public Criteria andInvoiceIdNotEqualTo(Long value) {
			addCriterion("invoice_id <>", value, "invoiceId");
			return (Criteria) this;
		}

		public Criteria andInvoiceIdGreaterThan(Long value) {
			addCriterion("invoice_id >", value, "invoiceId");
			return (Criteria) this;
		}

		public Criteria andInvoiceIdGreaterThanOrEqualTo(Long value) {
			addCriterion("invoice_id >=", value, "invoiceId");
			return (Criteria) this;
		}

		public Criteria andInvoiceIdLessThan(Long value) {
			addCriterion("invoice_id <", value, "invoiceId");
			return (Criteria) this;
		}

		public Criteria andInvoiceIdLessThanOrEqualTo(Long value) {
			addCriterion("invoice_id <=", value, "invoiceId");
			return (Criteria) this;
		}

		public Criteria andInvoiceIdIn(List<Long> values) {
			addCriterion("invoice_id in", values, "invoiceId");
			return (Criteria) this;
		}

		public Criteria andInvoiceIdNotIn(List<Long> values) {
			addCriterion("invoice_id not in", values, "invoiceId");
			return (Criteria) this;
		}

		public Criteria andInvoiceIdBetween(Long value1, Long value2) {
			addCriterion("invoice_id between", value1, value2, "invoiceId");
			return (Criteria) this;
		}

		public Criteria andInvoiceIdNotBetween(Long value1, Long value2) {
			addCriterion("invoice_id not between", value1, value2, "invoiceId");
			return (Criteria) this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("type is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("type is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(Short value) {
			addCriterion("type =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(Short value) {
			addCriterion("type <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(Short value) {
			addCriterion("type >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(Short value) {
			addCriterion("type >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(Short value) {
			addCriterion("type <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(Short value) {
			addCriterion("type <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<Short> values) {
			addCriterion("type in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<Short> values) {
			addCriterion("type not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(Short value1, Short value2) {
			addCriterion("type between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(Short value1, Short value2) {
			addCriterion("type not between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("title is null");
			return (Criteria) this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("title is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("title =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("title <>", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("title >", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("title >=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("title <", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("title <=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("title like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("title not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("title in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("title not in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("title between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("title not between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andProductTypeIsNull() {
			addCriterion("product_type is null");
			return (Criteria) this;
		}

		public Criteria andProductTypeIsNotNull() {
			addCriterion("product_type is not null");
			return (Criteria) this;
		}

		public Criteria andProductTypeEqualTo(Short value) {
			addCriterion("product_type =", value, "productType");
			return (Criteria) this;
		}

		public Criteria andProductTypeNotEqualTo(Short value) {
			addCriterion("product_type <>", value, "productType");
			return (Criteria) this;
		}

		public Criteria andProductTypeGreaterThan(Short value) {
			addCriterion("product_type >", value, "productType");
			return (Criteria) this;
		}

		public Criteria andProductTypeGreaterThanOrEqualTo(Short value) {
			addCriterion("product_type >=", value, "productType");
			return (Criteria) this;
		}

		public Criteria andProductTypeLessThan(Short value) {
			addCriterion("product_type <", value, "productType");
			return (Criteria) this;
		}

		public Criteria andProductTypeLessThanOrEqualTo(Short value) {
			addCriterion("product_type <=", value, "productType");
			return (Criteria) this;
		}

		public Criteria andProductTypeIn(List<Short> values) {
			addCriterion("product_type in", values, "productType");
			return (Criteria) this;
		}

		public Criteria andProductTypeNotIn(List<Short> values) {
			addCriterion("product_type not in", values, "productType");
			return (Criteria) this;
		}

		public Criteria andProductTypeBetween(Short value1, Short value2) {
			addCriterion("product_type between", value1, value2, "productType");
			return (Criteria) this;
		}

		public Criteria andProductTypeNotBetween(Short value1, Short value2) {
			addCriterion("product_type not between", value1, value2,
					"productType");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2,
					"createTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table invoice
	 * @mbggenerated  Fri Jul 18 11:24:51 CST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table invoice
     *
     * @mbggenerated do_not_delete_during_merge Thu Jul 17 21:42:51 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}