package com.mission.shop.order.dao.model;

import java.io.Serializable;
import java.util.Date;

public class OrderAddress implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_address.id
	 * @mbggenerated  Tue Nov 11 10:27:12 CST 2014
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_address.order_id
	 * @mbggenerated  Tue Nov 11 10:27:12 CST 2014
	 */
	private Long orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_address.consignee
	 * @mbggenerated  Tue Nov 11 10:27:12 CST 2014
	 */
	private String consignee;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_address.phone_num
	 * @mbggenerated  Tue Nov 11 10:27:12 CST 2014
	 */
	private String phoneNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_address.post_code
	 * @mbggenerated  Tue Nov 11 10:27:12 CST 2014
	 */
	private String postCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_address.address
	 * @mbggenerated  Tue Nov 11 10:27:12 CST 2014
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_address.province
	 * @mbggenerated  Tue Nov 11 10:27:12 CST 2014
	 */
	private String province;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_address.city
	 * @mbggenerated  Tue Nov 11 10:27:12 CST 2014
	 */
	private String city;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_address.county
	 * @mbggenerated  Tue Nov 11 10:27:12 CST 2014
	 */
	private String county;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_address.express_id
	 * @mbggenerated  Tue Nov 11 10:27:12 CST 2014
	 */
	private Long expressId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_address.express_name
	 * @mbggenerated  Tue Nov 11 10:27:12 CST 2014
	 */
	private String expressName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_address.express_no
	 * @mbggenerated  Tue Nov 11 10:27:12 CST 2014
	 */
	private String expressNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_address.create_time
	 * @mbggenerated  Tue Nov 11 10:27:12 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table order_address
	 * @mbggenerated  Tue Nov 11 10:27:12 CST 2014
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_address.id
	 * @return  the value of order_address.id
	 * @mbggenerated  Tue Nov 11 10:27:12 CST 2014
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_address.id
	 * @param id  the value for order_address.id
	 * @mbggenerated  Tue Nov 11 10:27:12 CST 2014
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_address.order_id
	 * @return  the value of order_address.order_id
	 * @mbggenerated  Tue Nov 11 10:27:12 CST 2014
	 */
	public Long getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_address.order_id
	 * @param orderId  the value for order_address.order_id
	 * @mbggenerated  Tue Nov 11 10:27:12 CST 2014
	 */
	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_address.consignee
	 * @return  the value of order_address.consignee
	 * @mbggenerated  Tue Nov 11 10:27:12 CST 2014
	 */
	public String getConsignee() {
		return consignee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_address.consignee
	 * @param consignee  the value for order_address.consignee
	 * @mbggenerated  Tue Nov 11 10:27:12 CST 2014
	 */
	public void setConsignee(String consignee) {
		this.consignee = consignee == null ? null : consignee.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_address.phone_num
	 * @return  the value of order_address.phone_num
	 * @mbggenerated  Tue Nov 11 10:27:12 CST 2014
	 */
	public String getPhoneNum() {
		return phoneNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_address.phone_num
	 * @param phoneNum  the value for order_address.phone_num
	 * @mbggenerated  Tue Nov 11 10:27:12 CST 2014
	 */
	public void setPhoneNum(String phoneNum) {
		this.phoneNum = phoneNum == null ? null : phoneNum.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_address.post_code
	 * @return  the value of order_address.post_code
	 * @mbggenerated  Tue Nov 11 10:27:12 CST 2014
	 */
	public String getPostCode() {
		return postCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_address.post_code
	 * @param postCode  the value for order_address.post_code
	 * @mbggenerated  Tue Nov 11 10:27:12 CST 2014
	 */
	public void setPostCode(String postCode) {
		this.postCode = postCode == null ? null : postCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_address.address
	 * @return  the value of order_address.address
	 * @mbggenerated  Tue Nov 11 10:27:12 CST 2014
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_address.address
	 * @param address  the value for order_address.address
	 * @mbggenerated  Tue Nov 11 10:27:12 CST 2014
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_address.province
	 * @return  the value of order_address.province
	 * @mbggenerated  Tue Nov 11 10:27:12 CST 2014
	 */
	public String getProvince() {
		return province;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_address.province
	 * @param province  the value for order_address.province
	 * @mbggenerated  Tue Nov 11 10:27:12 CST 2014
	 */
	public void setProvince(String province) {
		this.province = province == null ? null : province.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_address.city
	 * @return  the value of order_address.city
	 * @mbggenerated  Tue Nov 11 10:27:12 CST 2014
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_address.city
	 * @param city  the value for order_address.city
	 * @mbggenerated  Tue Nov 11 10:27:12 CST 2014
	 */
	public void setCity(String city) {
		this.city = city == null ? null : city.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_address.county
	 * @return  the value of order_address.county
	 * @mbggenerated  Tue Nov 11 10:27:12 CST 2014
	 */
	public String getCounty() {
		return county;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_address.county
	 * @param county  the value for order_address.county
	 * @mbggenerated  Tue Nov 11 10:27:12 CST 2014
	 */
	public void setCounty(String county) {
		this.county = county == null ? null : county.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_address.express_id
	 * @return  the value of order_address.express_id
	 * @mbggenerated  Tue Nov 11 10:27:12 CST 2014
	 */
	public Long getExpressId() {
		return expressId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_address.express_id
	 * @param expressId  the value for order_address.express_id
	 * @mbggenerated  Tue Nov 11 10:27:12 CST 2014
	 */
	public void setExpressId(Long expressId) {
		this.expressId = expressId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_address.express_name
	 * @return  the value of order_address.express_name
	 * @mbggenerated  Tue Nov 11 10:27:12 CST 2014
	 */
	public String getExpressName() {
		return expressName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_address.express_name
	 * @param expressName  the value for order_address.express_name
	 * @mbggenerated  Tue Nov 11 10:27:12 CST 2014
	 */
	public void setExpressName(String expressName) {
		this.expressName = expressName == null ? null : expressName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_address.express_no
	 * @return  the value of order_address.express_no
	 * @mbggenerated  Tue Nov 11 10:27:12 CST 2014
	 */
	public String getExpressNo() {
		return expressNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_address.express_no
	 * @param expressNo  the value for order_address.express_no
	 * @mbggenerated  Tue Nov 11 10:27:12 CST 2014
	 */
	public void setExpressNo(String expressNo) {
		this.expressNo = expressNo == null ? null : expressNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_address.create_time
	 * @return  the value of order_address.create_time
	 * @mbggenerated  Tue Nov 11 10:27:12 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_address.create_time
	 * @param createTime  the value for order_address.create_time
	 * @mbggenerated  Tue Nov 11 10:27:12 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}