package com.mission.shop.order.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrderExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table trade_order
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table trade_order
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table trade_order
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_order
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public OrderExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_order
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_order
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_order
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_order
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_order
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_order
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_order
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_order
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_order
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_order
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table trade_order
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andOrderIdIsNull() {
			addCriterion("order_id is null");
			return (Criteria) this;
		}

		public Criteria andOrderIdIsNotNull() {
			addCriterion("order_id is not null");
			return (Criteria) this;
		}

		public Criteria andOrderIdEqualTo(Long value) {
			addCriterion("order_id =", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotEqualTo(Long value) {
			addCriterion("order_id <>", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdGreaterThan(Long value) {
			addCriterion("order_id >", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdGreaterThanOrEqualTo(Long value) {
			addCriterion("order_id >=", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdLessThan(Long value) {
			addCriterion("order_id <", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdLessThanOrEqualTo(Long value) {
			addCriterion("order_id <=", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdIn(List<Long> values) {
			addCriterion("order_id in", values, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotIn(List<Long> values) {
			addCriterion("order_id not in", values, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdBetween(Long value1, Long value2) {
			addCriterion("order_id between", value1, value2, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotBetween(Long value1, Long value2) {
			addCriterion("order_id not between", value1, value2, "orderId");
			return (Criteria) this;
		}

		public Criteria andShopIdIsNull() {
			addCriterion("shop_id is null");
			return (Criteria) this;
		}

		public Criteria andShopIdIsNotNull() {
			addCriterion("shop_id is not null");
			return (Criteria) this;
		}

		public Criteria andShopIdEqualTo(Long value) {
			addCriterion("shop_id =", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdNotEqualTo(Long value) {
			addCriterion("shop_id <>", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdGreaterThan(Long value) {
			addCriterion("shop_id >", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdGreaterThanOrEqualTo(Long value) {
			addCriterion("shop_id >=", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdLessThan(Long value) {
			addCriterion("shop_id <", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdLessThanOrEqualTo(Long value) {
			addCriterion("shop_id <=", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdIn(List<Long> values) {
			addCriterion("shop_id in", values, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdNotIn(List<Long> values) {
			addCriterion("shop_id not in", values, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdBetween(Long value1, Long value2) {
			addCriterion("shop_id between", value1, value2, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdNotBetween(Long value1, Long value2) {
			addCriterion("shop_id not between", value1, value2, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopNameIsNull() {
			addCriterion("shop_name is null");
			return (Criteria) this;
		}

		public Criteria andShopNameIsNotNull() {
			addCriterion("shop_name is not null");
			return (Criteria) this;
		}

		public Criteria andShopNameEqualTo(String value) {
			addCriterion("shop_name =", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameNotEqualTo(String value) {
			addCriterion("shop_name <>", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameGreaterThan(String value) {
			addCriterion("shop_name >", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameGreaterThanOrEqualTo(String value) {
			addCriterion("shop_name >=", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameLessThan(String value) {
			addCriterion("shop_name <", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameLessThanOrEqualTo(String value) {
			addCriterion("shop_name <=", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameLike(String value) {
			addCriterion("shop_name like", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameNotLike(String value) {
			addCriterion("shop_name not like", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameIn(List<String> values) {
			addCriterion("shop_name in", values, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameNotIn(List<String> values) {
			addCriterion("shop_name not in", values, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameBetween(String value1, String value2) {
			addCriterion("shop_name between", value1, value2, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameNotBetween(String value1, String value2) {
			addCriterion("shop_name not between", value1, value2, "shopName");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(Long value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(Long value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(Long value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(Long value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Long value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<Long> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<Long> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(Long value1, Long value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(Long value1, Long value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserNameIsNull() {
			addCriterion("user_name is null");
			return (Criteria) this;
		}

		public Criteria andUserNameIsNotNull() {
			addCriterion("user_name is not null");
			return (Criteria) this;
		}

		public Criteria andUserNameEqualTo(String value) {
			addCriterion("user_name =", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotEqualTo(String value) {
			addCriterion("user_name <>", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameGreaterThan(String value) {
			addCriterion("user_name >", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameGreaterThanOrEqualTo(String value) {
			addCriterion("user_name >=", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLessThan(String value) {
			addCriterion("user_name <", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLessThanOrEqualTo(String value) {
			addCriterion("user_name <=", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLike(String value) {
			addCriterion("user_name like", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotLike(String value) {
			addCriterion("user_name not like", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameIn(List<String> values) {
			addCriterion("user_name in", values, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotIn(List<String> values) {
			addCriterion("user_name not in", values, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameBetween(String value1, String value2) {
			addCriterion("user_name between", value1, value2, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotBetween(String value1, String value2) {
			addCriterion("user_name not between", value1, value2, "userName");
			return (Criteria) this;
		}

		public Criteria andSellerUserIdIsNull() {
			addCriterion("seller_user_id is null");
			return (Criteria) this;
		}

		public Criteria andSellerUserIdIsNotNull() {
			addCriterion("seller_user_id is not null");
			return (Criteria) this;
		}

		public Criteria andSellerUserIdEqualTo(Long value) {
			addCriterion("seller_user_id =", value, "sellerUserId");
			return (Criteria) this;
		}

		public Criteria andSellerUserIdNotEqualTo(Long value) {
			addCriterion("seller_user_id <>", value, "sellerUserId");
			return (Criteria) this;
		}

		public Criteria andSellerUserIdGreaterThan(Long value) {
			addCriterion("seller_user_id >", value, "sellerUserId");
			return (Criteria) this;
		}

		public Criteria andSellerUserIdGreaterThanOrEqualTo(Long value) {
			addCriterion("seller_user_id >=", value, "sellerUserId");
			return (Criteria) this;
		}

		public Criteria andSellerUserIdLessThan(Long value) {
			addCriterion("seller_user_id <", value, "sellerUserId");
			return (Criteria) this;
		}

		public Criteria andSellerUserIdLessThanOrEqualTo(Long value) {
			addCriterion("seller_user_id <=", value, "sellerUserId");
			return (Criteria) this;
		}

		public Criteria andSellerUserIdIn(List<Long> values) {
			addCriterion("seller_user_id in", values, "sellerUserId");
			return (Criteria) this;
		}

		public Criteria andSellerUserIdNotIn(List<Long> values) {
			addCriterion("seller_user_id not in", values, "sellerUserId");
			return (Criteria) this;
		}

		public Criteria andSellerUserIdBetween(Long value1, Long value2) {
			addCriterion("seller_user_id between", value1, value2,
					"sellerUserId");
			return (Criteria) this;
		}

		public Criteria andSellerUserIdNotBetween(Long value1, Long value2) {
			addCriterion("seller_user_id not between", value1, value2,
					"sellerUserId");
			return (Criteria) this;
		}

		public Criteria andSellerUserNameIsNull() {
			addCriterion("seller_user_name is null");
			return (Criteria) this;
		}

		public Criteria andSellerUserNameIsNotNull() {
			addCriterion("seller_user_name is not null");
			return (Criteria) this;
		}

		public Criteria andSellerUserNameEqualTo(String value) {
			addCriterion("seller_user_name =", value, "sellerUserName");
			return (Criteria) this;
		}

		public Criteria andSellerUserNameNotEqualTo(String value) {
			addCriterion("seller_user_name <>", value, "sellerUserName");
			return (Criteria) this;
		}

		public Criteria andSellerUserNameGreaterThan(String value) {
			addCriterion("seller_user_name >", value, "sellerUserName");
			return (Criteria) this;
		}

		public Criteria andSellerUserNameGreaterThanOrEqualTo(String value) {
			addCriterion("seller_user_name >=", value, "sellerUserName");
			return (Criteria) this;
		}

		public Criteria andSellerUserNameLessThan(String value) {
			addCriterion("seller_user_name <", value, "sellerUserName");
			return (Criteria) this;
		}

		public Criteria andSellerUserNameLessThanOrEqualTo(String value) {
			addCriterion("seller_user_name <=", value, "sellerUserName");
			return (Criteria) this;
		}

		public Criteria andSellerUserNameLike(String value) {
			addCriterion("seller_user_name like", value, "sellerUserName");
			return (Criteria) this;
		}

		public Criteria andSellerUserNameNotLike(String value) {
			addCriterion("seller_user_name not like", value, "sellerUserName");
			return (Criteria) this;
		}

		public Criteria andSellerUserNameIn(List<String> values) {
			addCriterion("seller_user_name in", values, "sellerUserName");
			return (Criteria) this;
		}

		public Criteria andSellerUserNameNotIn(List<String> values) {
			addCriterion("seller_user_name not in", values, "sellerUserName");
			return (Criteria) this;
		}

		public Criteria andSellerUserNameBetween(String value1, String value2) {
			addCriterion("seller_user_name between", value1, value2,
					"sellerUserName");
			return (Criteria) this;
		}

		public Criteria andSellerUserNameNotBetween(String value1, String value2) {
			addCriterion("seller_user_name not between", value1, value2,
					"sellerUserName");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Short value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Short value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Short value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Short value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Short value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Short value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Short> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Short> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Short value1, Short value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Short value1, Short value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andPayTypeIsNull() {
			addCriterion("pay_type is null");
			return (Criteria) this;
		}

		public Criteria andPayTypeIsNotNull() {
			addCriterion("pay_type is not null");
			return (Criteria) this;
		}

		public Criteria andPayTypeEqualTo(Short value) {
			addCriterion("pay_type =", value, "payType");
			return (Criteria) this;
		}

		public Criteria andPayTypeNotEqualTo(Short value) {
			addCriterion("pay_type <>", value, "payType");
			return (Criteria) this;
		}

		public Criteria andPayTypeGreaterThan(Short value) {
			addCriterion("pay_type >", value, "payType");
			return (Criteria) this;
		}

		public Criteria andPayTypeGreaterThanOrEqualTo(Short value) {
			addCriterion("pay_type >=", value, "payType");
			return (Criteria) this;
		}

		public Criteria andPayTypeLessThan(Short value) {
			addCriterion("pay_type <", value, "payType");
			return (Criteria) this;
		}

		public Criteria andPayTypeLessThanOrEqualTo(Short value) {
			addCriterion("pay_type <=", value, "payType");
			return (Criteria) this;
		}

		public Criteria andPayTypeIn(List<Short> values) {
			addCriterion("pay_type in", values, "payType");
			return (Criteria) this;
		}

		public Criteria andPayTypeNotIn(List<Short> values) {
			addCriterion("pay_type not in", values, "payType");
			return (Criteria) this;
		}

		public Criteria andPayTypeBetween(Short value1, Short value2) {
			addCriterion("pay_type between", value1, value2, "payType");
			return (Criteria) this;
		}

		public Criteria andPayTypeNotBetween(Short value1, Short value2) {
			addCriterion("pay_type not between", value1, value2, "payType");
			return (Criteria) this;
		}

		public Criteria andAmountIsNull() {
			addCriterion("amount is null");
			return (Criteria) this;
		}

		public Criteria andAmountIsNotNull() {
			addCriterion("amount is not null");
			return (Criteria) this;
		}

		public Criteria andAmountEqualTo(Integer value) {
			addCriterion("amount =", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotEqualTo(Integer value) {
			addCriterion("amount <>", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountGreaterThan(Integer value) {
			addCriterion("amount >", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountGreaterThanOrEqualTo(Integer value) {
			addCriterion("amount >=", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountLessThan(Integer value) {
			addCriterion("amount <", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountLessThanOrEqualTo(Integer value) {
			addCriterion("amount <=", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountIn(List<Integer> values) {
			addCriterion("amount in", values, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotIn(List<Integer> values) {
			addCriterion("amount not in", values, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountBetween(Integer value1, Integer value2) {
			addCriterion("amount between", value1, value2, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotBetween(Integer value1, Integer value2) {
			addCriterion("amount not between", value1, value2, "amount");
			return (Criteria) this;
		}

		public Criteria andExpressFeeIsNull() {
			addCriterion("express_fee is null");
			return (Criteria) this;
		}

		public Criteria andExpressFeeIsNotNull() {
			addCriterion("express_fee is not null");
			return (Criteria) this;
		}

		public Criteria andExpressFeeEqualTo(Integer value) {
			addCriterion("express_fee =", value, "expressFee");
			return (Criteria) this;
		}

		public Criteria andExpressFeeNotEqualTo(Integer value) {
			addCriterion("express_fee <>", value, "expressFee");
			return (Criteria) this;
		}

		public Criteria andExpressFeeGreaterThan(Integer value) {
			addCriterion("express_fee >", value, "expressFee");
			return (Criteria) this;
		}

		public Criteria andExpressFeeGreaterThanOrEqualTo(Integer value) {
			addCriterion("express_fee >=", value, "expressFee");
			return (Criteria) this;
		}

		public Criteria andExpressFeeLessThan(Integer value) {
			addCriterion("express_fee <", value, "expressFee");
			return (Criteria) this;
		}

		public Criteria andExpressFeeLessThanOrEqualTo(Integer value) {
			addCriterion("express_fee <=", value, "expressFee");
			return (Criteria) this;
		}

		public Criteria andExpressFeeIn(List<Integer> values) {
			addCriterion("express_fee in", values, "expressFee");
			return (Criteria) this;
		}

		public Criteria andExpressFeeNotIn(List<Integer> values) {
			addCriterion("express_fee not in", values, "expressFee");
			return (Criteria) this;
		}

		public Criteria andExpressFeeBetween(Integer value1, Integer value2) {
			addCriterion("express_fee between", value1, value2, "expressFee");
			return (Criteria) this;
		}

		public Criteria andExpressFeeNotBetween(Integer value1, Integer value2) {
			addCriterion("express_fee not between", value1, value2,
					"expressFee");
			return (Criteria) this;
		}

		public Criteria andUseIntegralIsNull() {
			addCriterion("use_integral is null");
			return (Criteria) this;
		}

		public Criteria andUseIntegralIsNotNull() {
			addCriterion("use_integral is not null");
			return (Criteria) this;
		}

		public Criteria andUseIntegralEqualTo(Integer value) {
			addCriterion("use_integral =", value, "useIntegral");
			return (Criteria) this;
		}

		public Criteria andUseIntegralNotEqualTo(Integer value) {
			addCriterion("use_integral <>", value, "useIntegral");
			return (Criteria) this;
		}

		public Criteria andUseIntegralGreaterThan(Integer value) {
			addCriterion("use_integral >", value, "useIntegral");
			return (Criteria) this;
		}

		public Criteria andUseIntegralGreaterThanOrEqualTo(Integer value) {
			addCriterion("use_integral >=", value, "useIntegral");
			return (Criteria) this;
		}

		public Criteria andUseIntegralLessThan(Integer value) {
			addCriterion("use_integral <", value, "useIntegral");
			return (Criteria) this;
		}

		public Criteria andUseIntegralLessThanOrEqualTo(Integer value) {
			addCriterion("use_integral <=", value, "useIntegral");
			return (Criteria) this;
		}

		public Criteria andUseIntegralIn(List<Integer> values) {
			addCriterion("use_integral in", values, "useIntegral");
			return (Criteria) this;
		}

		public Criteria andUseIntegralNotIn(List<Integer> values) {
			addCriterion("use_integral not in", values, "useIntegral");
			return (Criteria) this;
		}

		public Criteria andUseIntegralBetween(Integer value1, Integer value2) {
			addCriterion("use_integral between", value1, value2, "useIntegral");
			return (Criteria) this;
		}

		public Criteria andUseIntegralNotBetween(Integer value1, Integer value2) {
			addCriterion("use_integral not between", value1, value2,
					"useIntegral");
			return (Criteria) this;
		}

		public Criteria andSentIntegralIsNull() {
			addCriterion("sent_integral is null");
			return (Criteria) this;
		}

		public Criteria andSentIntegralIsNotNull() {
			addCriterion("sent_integral is not null");
			return (Criteria) this;
		}

		public Criteria andSentIntegralEqualTo(Integer value) {
			addCriterion("sent_integral =", value, "sentIntegral");
			return (Criteria) this;
		}

		public Criteria andSentIntegralNotEqualTo(Integer value) {
			addCriterion("sent_integral <>", value, "sentIntegral");
			return (Criteria) this;
		}

		public Criteria andSentIntegralGreaterThan(Integer value) {
			addCriterion("sent_integral >", value, "sentIntegral");
			return (Criteria) this;
		}

		public Criteria andSentIntegralGreaterThanOrEqualTo(Integer value) {
			addCriterion("sent_integral >=", value, "sentIntegral");
			return (Criteria) this;
		}

		public Criteria andSentIntegralLessThan(Integer value) {
			addCriterion("sent_integral <", value, "sentIntegral");
			return (Criteria) this;
		}

		public Criteria andSentIntegralLessThanOrEqualTo(Integer value) {
			addCriterion("sent_integral <=", value, "sentIntegral");
			return (Criteria) this;
		}

		public Criteria andSentIntegralIn(List<Integer> values) {
			addCriterion("sent_integral in", values, "sentIntegral");
			return (Criteria) this;
		}

		public Criteria andSentIntegralNotIn(List<Integer> values) {
			addCriterion("sent_integral not in", values, "sentIntegral");
			return (Criteria) this;
		}

		public Criteria andSentIntegralBetween(Integer value1, Integer value2) {
			addCriterion("sent_integral between", value1, value2,
					"sentIntegral");
			return (Criteria) this;
		}

		public Criteria andSentIntegralNotBetween(Integer value1, Integer value2) {
			addCriterion("sent_integral not between", value1, value2,
					"sentIntegral");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("remark is null");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("remark is not null");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("remark =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("remark <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("remark >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("remark >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("remark <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("remark <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("remark like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("remark not like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkIn(List<String> values) {
			addCriterion("remark in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("remark not in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("remark between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("remark not between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andSellerRemarkIsNull() {
			addCriterion("seller_remark is null");
			return (Criteria) this;
		}

		public Criteria andSellerRemarkIsNotNull() {
			addCriterion("seller_remark is not null");
			return (Criteria) this;
		}

		public Criteria andSellerRemarkEqualTo(String value) {
			addCriterion("seller_remark =", value, "sellerRemark");
			return (Criteria) this;
		}

		public Criteria andSellerRemarkNotEqualTo(String value) {
			addCriterion("seller_remark <>", value, "sellerRemark");
			return (Criteria) this;
		}

		public Criteria andSellerRemarkGreaterThan(String value) {
			addCriterion("seller_remark >", value, "sellerRemark");
			return (Criteria) this;
		}

		public Criteria andSellerRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("seller_remark >=", value, "sellerRemark");
			return (Criteria) this;
		}

		public Criteria andSellerRemarkLessThan(String value) {
			addCriterion("seller_remark <", value, "sellerRemark");
			return (Criteria) this;
		}

		public Criteria andSellerRemarkLessThanOrEqualTo(String value) {
			addCriterion("seller_remark <=", value, "sellerRemark");
			return (Criteria) this;
		}

		public Criteria andSellerRemarkLike(String value) {
			addCriterion("seller_remark like", value, "sellerRemark");
			return (Criteria) this;
		}

		public Criteria andSellerRemarkNotLike(String value) {
			addCriterion("seller_remark not like", value, "sellerRemark");
			return (Criteria) this;
		}

		public Criteria andSellerRemarkIn(List<String> values) {
			addCriterion("seller_remark in", values, "sellerRemark");
			return (Criteria) this;
		}

		public Criteria andSellerRemarkNotIn(List<String> values) {
			addCriterion("seller_remark not in", values, "sellerRemark");
			return (Criteria) this;
		}

		public Criteria andSellerRemarkBetween(String value1, String value2) {
			addCriterion("seller_remark between", value1, value2,
					"sellerRemark");
			return (Criteria) this;
		}

		public Criteria andSellerRemarkNotBetween(String value1, String value2) {
			addCriterion("seller_remark not between", value1, value2,
					"sellerRemark");
			return (Criteria) this;
		}

		public Criteria andVersionIsNull() {
			addCriterion("version is null");
			return (Criteria) this;
		}

		public Criteria andVersionIsNotNull() {
			addCriterion("version is not null");
			return (Criteria) this;
		}

		public Criteria andVersionEqualTo(Integer value) {
			addCriterion("version =", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotEqualTo(Integer value) {
			addCriterion("version <>", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionGreaterThan(Integer value) {
			addCriterion("version >", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
			addCriterion("version >=", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLessThan(Integer value) {
			addCriterion("version <", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLessThanOrEqualTo(Integer value) {
			addCriterion("version <=", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionIn(List<Integer> values) {
			addCriterion("version in", values, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotIn(List<Integer> values) {
			addCriterion("version not in", values, "version");
			return (Criteria) this;
		}

		public Criteria andVersionBetween(Integer value1, Integer value2) {
			addCriterion("version between", value1, value2, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotBetween(Integer value1, Integer value2) {
			addCriterion("version not between", value1, value2, "version");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2,
					"createTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("update_time is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("update_time is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("update_time =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("update_time <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("update_time >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("update_time >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("update_time <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("update_time <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterion("update_time in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterion("update_time not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("update_time between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("update_time not between", value1, value2,
					"updateTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table trade_order
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table trade_order
     *
     * @mbggenerated do_not_delete_during_merge Thu Jul 17 21:42:51 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}