package com.mission.shop.order.dao.model;

import java.io.Serializable;
import java.util.Date;

public class OrderGoods implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_goods.id
	 * @mbggenerated  Fri Jul 18 11:24:51 CST 2014
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_goods.order_id
	 * @mbggenerated  Fri Jul 18 11:24:51 CST 2014
	 */
	private Long orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_goods.goods_id
	 * @mbggenerated  Fri Jul 18 11:24:51 CST 2014
	 */
	private Long goodsId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_goods.goods_name
	 * @mbggenerated  Fri Jul 18 11:24:51 CST 2014
	 */
	private String goodsName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_goods.price
	 * @mbggenerated  Fri Jul 18 11:24:51 CST 2014
	 */
	private Integer price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_goods.quanity
	 * @mbggenerated  Fri Jul 18 11:24:51 CST 2014
	 */
	private Integer quanity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_goods.create_time
	 * @mbggenerated  Fri Jul 18 11:24:51 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table order_goods
	 * @mbggenerated  Fri Jul 18 11:24:51 CST 2014
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_goods.id
	 * @return  the value of order_goods.id
	 * @mbggenerated  Fri Jul 18 11:24:51 CST 2014
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_goods.id
	 * @param id  the value for order_goods.id
	 * @mbggenerated  Fri Jul 18 11:24:51 CST 2014
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_goods.order_id
	 * @return  the value of order_goods.order_id
	 * @mbggenerated  Fri Jul 18 11:24:51 CST 2014
	 */
	public Long getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_goods.order_id
	 * @param orderId  the value for order_goods.order_id
	 * @mbggenerated  Fri Jul 18 11:24:51 CST 2014
	 */
	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_goods.goods_id
	 * @return  the value of order_goods.goods_id
	 * @mbggenerated  Fri Jul 18 11:24:51 CST 2014
	 */
	public Long getGoodsId() {
		return goodsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_goods.goods_id
	 * @param goodsId  the value for order_goods.goods_id
	 * @mbggenerated  Fri Jul 18 11:24:51 CST 2014
	 */
	public void setGoodsId(Long goodsId) {
		this.goodsId = goodsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_goods.goods_name
	 * @return  the value of order_goods.goods_name
	 * @mbggenerated  Fri Jul 18 11:24:51 CST 2014
	 */
	public String getGoodsName() {
		return goodsName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_goods.goods_name
	 * @param goodsName  the value for order_goods.goods_name
	 * @mbggenerated  Fri Jul 18 11:24:51 CST 2014
	 */
	public void setGoodsName(String goodsName) {
		this.goodsName = goodsName == null ? null : goodsName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_goods.price
	 * @return  the value of order_goods.price
	 * @mbggenerated  Fri Jul 18 11:24:51 CST 2014
	 */
	public Integer getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_goods.price
	 * @param price  the value for order_goods.price
	 * @mbggenerated  Fri Jul 18 11:24:51 CST 2014
	 */
	public void setPrice(Integer price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_goods.quanity
	 * @return  the value of order_goods.quanity
	 * @mbggenerated  Fri Jul 18 11:24:51 CST 2014
	 */
	public Integer getQuanity() {
		return quanity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_goods.quanity
	 * @param quanity  the value for order_goods.quanity
	 * @mbggenerated  Fri Jul 18 11:24:51 CST 2014
	 */
	public void setQuanity(Integer quanity) {
		this.quanity = quanity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_goods.create_time
	 * @return  the value of order_goods.create_time
	 * @mbggenerated  Fri Jul 18 11:24:51 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_goods.create_time
	 * @param createTime  the value for order_goods.create_time
	 * @mbggenerated  Fri Jul 18 11:24:51 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}