package com.mission.shop.order.dao.model;

import java.io.Serializable;
import java.util.Date;

public class Order implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_order.order_id
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	private Long orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_order.shop_id
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	private Long shopId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_order.shop_name
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	private String shopName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_order.user_id
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_order.user_name
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_order.seller_user_id
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	private Long sellerUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_order.seller_user_name
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	private String sellerUserName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_order.status
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_order.pay_type
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	private Short payType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_order.amount
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	private Integer amount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_order.express_fee
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	private Integer expressFee;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_order.use_integral
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	private Integer useIntegral;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_order.sent_integral
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	private Integer sentIntegral;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_order.remark
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_order.seller_remark
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	private String sellerRemark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_order.version
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	private Integer version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_order.create_time
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trade_order.update_time
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table trade_order
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_order.order_id
	 * @return  the value of trade_order.order_id
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public Long getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_order.order_id
	 * @param orderId  the value for trade_order.order_id
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_order.shop_id
	 * @return  the value of trade_order.shop_id
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public Long getShopId() {
		return shopId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_order.shop_id
	 * @param shopId  the value for trade_order.shop_id
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public void setShopId(Long shopId) {
		this.shopId = shopId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_order.shop_name
	 * @return  the value of trade_order.shop_name
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public String getShopName() {
		return shopName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_order.shop_name
	 * @param shopName  the value for trade_order.shop_name
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public void setShopName(String shopName) {
		this.shopName = shopName == null ? null : shopName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_order.user_id
	 * @return  the value of trade_order.user_id
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_order.user_id
	 * @param userId  the value for trade_order.user_id
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_order.user_name
	 * @return  the value of trade_order.user_name
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_order.user_name
	 * @param userName  the value for trade_order.user_name
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_order.seller_user_id
	 * @return  the value of trade_order.seller_user_id
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public Long getSellerUserId() {
		return sellerUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_order.seller_user_id
	 * @param sellerUserId  the value for trade_order.seller_user_id
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public void setSellerUserId(Long sellerUserId) {
		this.sellerUserId = sellerUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_order.seller_user_name
	 * @return  the value of trade_order.seller_user_name
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public String getSellerUserName() {
		return sellerUserName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_order.seller_user_name
	 * @param sellerUserName  the value for trade_order.seller_user_name
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public void setSellerUserName(String sellerUserName) {
		this.sellerUserName = sellerUserName == null ? null : sellerUserName
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_order.status
	 * @return  the value of trade_order.status
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_order.status
	 * @param status  the value for trade_order.status
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_order.pay_type
	 * @return  the value of trade_order.pay_type
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public Short getPayType() {
		return payType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_order.pay_type
	 * @param payType  the value for trade_order.pay_type
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public void setPayType(Short payType) {
		this.payType = payType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_order.amount
	 * @return  the value of trade_order.amount
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public Integer getAmount() {
		return amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_order.amount
	 * @param amount  the value for trade_order.amount
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_order.express_fee
	 * @return  the value of trade_order.express_fee
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public Integer getExpressFee() {
		return expressFee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_order.express_fee
	 * @param expressFee  the value for trade_order.express_fee
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public void setExpressFee(Integer expressFee) {
		this.expressFee = expressFee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_order.use_integral
	 * @return  the value of trade_order.use_integral
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public Integer getUseIntegral() {
		return useIntegral;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_order.use_integral
	 * @param useIntegral  the value for trade_order.use_integral
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public void setUseIntegral(Integer useIntegral) {
		this.useIntegral = useIntegral;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_order.sent_integral
	 * @return  the value of trade_order.sent_integral
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public Integer getSentIntegral() {
		return sentIntegral;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_order.sent_integral
	 * @param sentIntegral  the value for trade_order.sent_integral
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public void setSentIntegral(Integer sentIntegral) {
		this.sentIntegral = sentIntegral;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_order.remark
	 * @return  the value of trade_order.remark
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_order.remark
	 * @param remark  the value for trade_order.remark
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_order.seller_remark
	 * @return  the value of trade_order.seller_remark
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public String getSellerRemark() {
		return sellerRemark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_order.seller_remark
	 * @param sellerRemark  the value for trade_order.seller_remark
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public void setSellerRemark(String sellerRemark) {
		this.sellerRemark = sellerRemark == null ? null : sellerRemark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_order.version
	 * @return  the value of trade_order.version
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_order.version
	 * @param version  the value for trade_order.version
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_order.create_time
	 * @return  the value of trade_order.create_time
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_order.create_time
	 * @param createTime  the value for trade_order.create_time
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trade_order.update_time
	 * @return  the value of trade_order.update_time
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trade_order.update_time
	 * @param updateTime  the value for trade_order.update_time
	 * @mbggenerated  Thu Nov 27 13:50:23 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}